### ISSUE TITLE
t is undefined on brand new install.

### ISSUE THREAD

**Issue by EvelynProto** [ActivityWatch/activitywatch#659] opened 2021-08-31 20:09 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- Windows 11 - Build 22000.168 
- v0.11.0 

## Describe the bug

On a brand new install, "t" is undefined on the "trends" page in the dashboard.

## To Reproduce

1. Install a fresh version of ActivityWatch
2. Open the dashboard
3. Navigate to the trends page

## Expected behavior

No trends show up, since its a new install, but the error shouldn't appear.

## Documentation

![image](https://user-images.githubusercontent.com/54776821/131568756-58208583-07a1-408e-b126-0cea6816462d.png)

**Comment by ErikBjare** [comment] 2021-09-02 11:09
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/611. A fix has been merged and will be in the next release (and is available today in the nightly builds, see: #507).

**Closed by ErikBjare** 2021-09-02 11:09 UTC
Labels: type: bug
