### ISSUE TITLE
System Tray Icon Does Not Respond On Pop!_OS 20.04

### ISSUE THREAD

**Issue by ankushdas9** [ActivityWatch/activitywatch#418] opened 2020-04-20 09:06 UTC
I can see the ActivityWatch icon on the system tray (https://i.imgur.com/22j5lTs.png) and hover over all the options - but when I click on them it does not work, especially

- Open dashboard
- Open log folder

So, I have to manually access http://localhost:5600 to check my activity.

## To Reproduce
Not really sure - try it on Ubuntu 20.04 or Pop!_OS 20.04 specifically to try if ActivityWatch works properly.

## Expected behavior
It should directly open the dashboard on my browser when I click on the dashboard option from the system tray.

Logfiles can be found in different places depending on the platform:
Not sure what log file should I share - aw-qt? aw-window? Please clarify

## Environment
 - ActivityWatch version: v0.9.2
 - OS: Pop!_OS 20.04

**Comment by ErikBjare** [comment] 2020-04-20 09:08
You already opened #412 which I closed because it's a duplicate of #208. Closing.

**Closed** 2020-04-20 09:08 UTC

**Comment by ankushdas9** [comment] 2020-04-20 09:09
> You already opened #412 which I closed because it's a duplicate of #208. Closing.

Yep, I closed it - sorry about that. Forgot that I reported it :-D
