### ISSUE TITLE
Unable to open app on v0.11.0 macOS Big Sur

### ISSUE THREAD

**Issue by AjayShanker-geek** [ActivityWatch/activitywatch#622] opened 2021-06-24 11:41 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: macOS Big Sur Version 11.4 (Macbook Air M1)
- **ActivityWatch version**: v0.11.0

## Describe the bug

After Updating to the new version of activitywatch, unable to open the app. Had to downgrade to v0.10.0 to continue using.

**Comment by RobertoMaurizzi** [comment] 2021-06-30 06:30
I'm seeing the same for v0.11.0 on Big Sur 11.4 but on an older Intel MacBook Pro.

Symptoms: app doesn't start on double click nor using Spotlight.
If you "show package contents" the app, you can execute `Contents/MacOS/aw-qt` that will run in a console window (and work quite normally, from what I can tell).
At the next reboot however the system will say the app is ruined and can't be opened and you need to reinstall from the original download archive.

**Comment by meain** [comment] 2021-07-01 04:01
![Screenshot 2021-07-01 at 9 30 14 AM](https://user-images.githubusercontent.com/14259816/124062761-f523cb00-da4e-11eb-8045-8f8f41f90a9d.png)

I am getting this error with `brew` installed version.

**Comment by ErikBjare** [comment] 2021-08-29 11:11
Duplicate of #630.

This issue was filed first, but the other one got more replies, so closing this once instead.

**Closed by ErikBjare** 2021-08-29 11:11 UTC
Labels: type: bug, duplicate, platform: macos
