### ISSUE TITLE
Incorrect week number displayed in Activity report

### ISSUE THREAD

**Issue by Ivor-T** [ActivityWatch/activitywatch#407] opened 2020-04-14 05:42 UTC
The week number on the activity report week page displays the wrong week number when first loading and when clicking the previous/next week buttons, but the week numbers jump to the correct week once you click on the bar graph.

First Loading:
![image](https://user-images.githubusercontent.com/63630478/79189651-9874ca00-7e22-11ea-869d-0d61e4e81ae8.png)

After clicking on Bar Graph:
![image](https://user-images.githubusercontent.com/63630478/79189718-c65a0e80-7e22-11ea-91e6-dc8f09f1dce7.png)

ActivityWatch Version: v0.8.4
on Windows10

(I'm a complete noob, hope I filed this bug correctly?)

**Comment by johan-bjareholt** [comment] 2020-04-14 07:07
The bug report is good, clearly explains how to reproduce it. Will take a look at it!

**Comment by ErikBjare** [comment] 2020-04-19 10:08
@johan-bjareholt Could this also have been fixed by https://github.com/ActivityWatch/aw-webui/pull/185?

**Comment by johan-bjareholt** [comment] 2020-04-19 17:46
@ErikBjare Good point, it should have been fixed by that PR yes. I don't have time to verify right now but pulling the latest master should be enough.

**Comment by johan-bjareholt** [comment] 2020-04-27 19:29
The issue is larger than https://github.com/ActivityWatch/aw-webui/pull/185

Seems to be some issue when you change the periodLength

**Closed** 2020-04-28 14:54 UTC
Labels: module: webui, size: small, type: bug

**Comment by ErikBjare** [comment] 2020-04-28 15:01
@johan-bjareholt Did that PR solve it or not?

**Comment by johan-bjareholt** [comment] 2020-04-28 19:39
That PR solves the issues yes!

**Comment by danvoronov** [comment] 2023-01-15 09:42
```
Activity for **2023 W52**

    Host:DESKTOP
    Time active:30h 11m 17s

    Query range: 2023-01-01—2023-01-08
```

Changed the start of the week to Sunday.
Should be 2023  W1 or 2022 W52
