### ISSUE TITLE
Can't Open Dashboard On Pop!_OS 20.04

### ISSUE THREAD

**Issue by ankushdas9** [ActivityWatch/activitywatch#412] opened 2020-04-17 06:17 UTC
The ActivityWatch icon appears on the system tray and also it tracks the activities correctly.

However, when I try to click on any option using the system tray icon, it doesn't do anything. So, I had to locally access the dashboard using http://localhost:5600

**Comment by ErikBjare** [comment] 2020-04-17 06:21
Duplicate of #208, closing.

**Closed** 2020-04-17 06:21 UTC
