### ISSUE TITLE
[Beta][Windows]: "request timeout" setting doesn't work

### ISSUE THREAD

**Issue by PetbkA** [ActivityWatch/activitywatch#979] opened 2023-10-31 05:44 UTC
- [x] I am on the [**latest beta v0.12.3b12**](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b12) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 LTSC 2021 (version 21H2) x64 EN
- **ActivityWatch version**: 0.12.3b**11**
- **Browser:** [Ungoogled Chromium 118.0.5993.118 x64](https://github.com/macchrome/winchrome/releases/tag/v118.5993.118-M118.0.5993.118-r1192594-Win64) with AW site in _Sites that can always use cookies_ list.

## Describe the bug

It seems that _Request Timeout_ parameter has stopped working. Can't get activities for `30 days` period 'cause of [**30** seconds timeout](https://github.com/ActivityWatch/activitywatch/assets/22843816/5ffeb090-6e70-4039-b249-93bca4b58299) while it should be **300** seconds.

## To Reproduce

1. Go to _Settings_ and change _Request Timeout_ value from `30` to `300`;
2. Close all AW tabs and restart _aw-server_ via tray;
3. Open _Activity_ screen and change time period to `30 days` - **NOK**: *AxiosError: timeout of **30**000ms exceeded* is raised, i.e. request timeout hasn't changed.

## Expected behavior

Categories will be shown after some time, more than 30 seconds, but less than 300 (worked OK in [beta v0.12.3b7](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b7)).

## Documentation

_aw-server_'s logs are [attached](https://github.com/ActivityWatch/activitywatch/files/13212430/aw-server_2023-10-31.zip). There are some errors, although they don't appear right when timeout error is raised. After some retries you can get _sqlite3.OperationalError: database is locked_ error which is hardly relevant to the bug:
```py
2023-10-31 08:33:12 [ERROR]: Exception on /api/0/buckets/aw-watcher-afk_petbka/events [GET]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 3252, in execute_sql
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 205, in get
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 226, in get_events
  File "aw_datastore\datastore.py", line 115, in get
  File "aw_datastore\storages\peewee.py", line 363, in get_events
  File "peewee.py", line 1972, in inner
  File "peewee.py", line 2043, in execute
  File "peewee.py", line 2216, in _execute
  File "peewee.py", line 3260, in execute
  File "peewee.py", line 3252, in execute_sql
  File "peewee.py", line 3020, in __exit__
  File "peewee.py", line 192, in reraise
  File "peewee.py", line 3252, in execute_sql
peewee.OperationalError: database is locked
```

**Comment by PetbkA** [comment] 2023-10-31 06:27
**v0.12.3b12**](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b12) - no changes, behavior as in beta 11. Updated issue description

**Comment by ErikBjare** [comment] 2023-11-15 14:24
Alright, so this is a tricky one.

It's caused by us switching to using server-stored settings, where the request timeout value is stored, but to access the settings we need aw-client initialized, which is where the timeout is passed in. Thus it ends up with the default timeout.

Fixing it now.

**Comment by ErikBjare** [comment] 2023-11-15 14:31
Fixed in https://github.com/ActivityWatch/aw-webui/commit/e05e80596df19d3595ecd8efb423cb2db1d5a339

Thanks for reporting!

**Closed by ErikBjare** 2023-11-15 14:31 UTC
Labels: type: bug

**Comment by PetbkA** [comment] 2023-11-17 05:35
**[ v0.12.3b13](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b13)** - fixed
