### ISSUE TITLE
11.0 gets flagged by Firefox as an virus

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/activitywatch#625] opened 2021-06-26 18:20 UTC
I don't know why or how to fix, just wanted to inform, that Firefox flaggs the installer as a virus or maleware, if you download the exe.

How to reproduce: Download the 11.0 installer for Windows using the newest Firefox version (89.0.2, 64bit)

**Comment by johan-bjareholt** [comment] 2021-06-27 08:43
Thanks for reporting, but i think this is a duplicate of https://github.com/ActivityWatch/activitywatch/issues/621
Are you sure that it's Firefox and not windows itself?

We can't do much about this except for telling antivirus vendors that it's a false positive, see issue https://github.com/ActivityWatch/activitywatch/issues/181

**Closed by johan-bjareholt** 2021-06-27 08:43 UTC

**Comment by kazerniel** [comment] 2021-07-19 17:58
It really does seem like it's Firefox that labels it as virus.

![image](https://user-images.githubusercontent.com/5689996/126205241-641cf51a-8027-40e7-b21d-b31a38f03ef3.png)

---
![image](https://user-images.githubusercontent.com/5689996/126205284-62129d7d-384e-4761-9856-d2613aec2f20.png)

Nothing happens if I click on Allow download.
