### ISSUE TITLE
Category name edit, also affects sister category

### ISSUE THREAD

**Issue by Chuhtra** [ActivityWatch/activitywatch#361] opened 2020-03-05 15:36 UTC
Trying to edit the category name of a newly made category, also changed the category name of the also newly made sister category. 

Steps I can reproduce it with:
1) Make a new category for testing.
2) Click fast on the green cross, to create 2 subcategories of this category.
3) Any edit to the first subcategory is copied to the second one, and vice versa.

Expected behavior would be for the edit to be contained to its target.

I am in Linux (Manjaro) with aw v0.8.4, using firefox.

 I solved it by deleting and recreating the "second" sister category. Trying to delete the "first" of the 2 sister categories sometimes didn't work.

**Comment by ErikBjare** [comment] 2020-03-05 15:39
I don't understand the behavior. Please follow the issue template and  provide step by step instructions to reproduce.

**Comment by Skarfrael** [comment] 2020-03-05 15:52
> I don't understand the behavior. Please follow the issue template and provide step by step instructions to reproduce.

Sorry, I was in a hurry. I edited the post.

**Comment by ErikBjare** [comment] 2020-03-08 08:45
Alright, so this seems to happen when two sister categories have the same name (which happens when they are created in succession with their default name).

Fixing this could be done by opening the edit dialog for the user directly when a child category is created (which is what we should do anyway).

**Comment by Skarfrael** [comment] 2020-03-08 10:01
I agree! Having said that, how come you don't assign a specific id to each category for things like these? Much like a database works. I'd say it would be more future proof than basing action on category's name.

**Comment by xylix** [comment] 2020-03-08 10:03
Actually having unique id's for identifying categories internally and separately having a "displayname" for every category that the user could change would also improve the logic in renaming backend-stored categories (which is a feature I'm currently working on.) 

Good idea.

**Comment by abhirupdutta0** [comment] 2020-03-09 06:07
> Alright, so this seems to happen when two sister categories have the same name (which happens when they are created in succession with their default name).
> 
> Fixing this could be done by opening the edit dialog for the user directly when a child category is created (which is what we should do anyway).

The issue I rasied actually has another bug too.The renaming of the first media category, and the subsequent error actually creates the new entertainment category shown in the gif.

**Comment by billangli** [comment] 2020-12-27 00:49
Hey @xylix, do you have any updates on this issue? I'd be happy to help/take over :)

**Comment by ErikBjare** [comment] 2020-12-28 18:53
@billangli I don't think @xylix ever picked it up, have a go at it!

**Comment by billangli** [comment] 2021-01-09 01:55
Hey @ErikBjare, I fixed the webapp and I changed it to use id to identify categories instead of name. I am currently figuring out what parts of the backend I need to change. It might take some time because I'm new with Rust :smile:

**Comment by ErikBjare** [comment] 2021-01-09 10:39
@billangli I don't think the Rust part needs to be changed? You should just be able to strip the ID's out before sending them in the query. Submit a PR for the web UI changes and I'll have a look :slightly_smiling_face:

**Comment by billangli** [comment] 2021-02-02 17:26
Dang I'm been pretty busy with school lately, but I'll come back and work on this this week :)

**Comment by ErikBjare** [comment] 2021-08-18 09:55
I think some of these issues have been fixed in v0.11, but iirc some issues still remain.

**Comment by yumemio** [comment] 2021-11-16 21:46
This issue appears to happen when the user removes a category, then updates another. I am working on a fix.

**Closed** 2021-11-22 13:31 UTC
Labels: type: bug

**Comment by ErikBjare** [comment] 2021-11-22 13:32
Finally fixed in https://github.com/ActivityWatch/aw-webui/pull/310, thanks @yumemio!
