### ISSUE TITLE
Double buckets

### ISSUE THREAD

**Issue by rtpHarry** [ActivityWatch/activitywatch#414] opened 2020-04-17 20:46 UTC
I've managed to confuse things:

![image](https://user-images.githubusercontent.com/1038062/79612363-75813900-80f4-11ea-84ac-57f40095d027.png)

It seems that it has two different names for my computer. I changed the name a while back and I'm sure its used it in places, for example my bluetooth has announced that it was connecting to MBP instead of the full original name, but I don't know if I have rebooted since then.

However, the last time I rebooted I had a strange issue where the mouse cursor got stuck as a magnifying glass with a +. Seems others have had it. I don't think its anything to do with this app but I'm just giving the background because I force quit my computer using CONTROL + OPTION + SHIFT for 7 seconds, then press POWER.

So there are two ideas for where the bug might be coming from:

  1. changing the computer name
  1. force rebooting the computer

**Comment by rtpHarry** [comment] 2020-04-17 20:51
Or 3, this isn't technically a bug, its just the computer has rebooted and now puts it in a different bucket for the different name...

**Comment by johan-bjareholt** [comment] 2020-07-30 19:46
The issue is from changing the computer name, but activitywatch did not realize that it changed name until you restarted activitywatch (in your case rebooted the computer).

This is a minor issue on our end, we have a long-term plan to make the computer not dependent on the computer name but that's not finished yet. (See this issue on the section "hostname to device ID" https://github.com/ActivityWatch/activitywatch/issues/424).

Closing this issue as it's essentially a duplicate of #424. It is possible to manually merge buckets however but it's very fiddly currently unfortunately.

https://github.com/ActivityWatch/activitywatch/issues/454#issuecomment-663939508

**Closed by johan-bjareholt** 2020-07-30 19:46 UTC
