### ISSUE TITLE
Issue while executing the .exe file

### ISSUE THREAD

**Issue by nagapoornima22** [ActivityWatch/activitywatch#473] opened 2020-08-18 10:35 UTC
I have successfully run the command make build with no issues.
Able to create the .exe file on windows machine and ubuntu machine.

While executing the .exe file not able to install the application, giving me the issue

![Capture](https://user-images.githubusercontent.com/54053687/90502981-565eea80-e16c-11ea-9374-13bea7a3f58d.PNG)

Please help me in taking it forward

**Comment by doamatto** [comment] 2020-09-06 07:13
Possible dupe of #288

**Comment by ErikBjare** [comment] 2020-09-13 10:45
The folder in the screenshot doesn't contain all the files needed. I can't see the path due to the crop, but you're probably not running the correct files. 

The build output should be in `dist/activitywatch`, and should contain subfolders for aw-server, aw-watcher-window/afk.

**Closed by ErikBjare** 2020-09-13 10:45 UTC
