### ISSUE TITLE
Unable to record game Apex (r5apex.exe) usage time

### ISSUE THREAD

**Issue by suiahae** [ActivityWatch/activitywatch#1004] opened 2024-01-03 15:41 UTC
- [x ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x ] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11 23H2 22631.2861
- **ActivityWatch version**: v0.12.2 & v0.12.3b15

## Describe the bug

Unable to record game **Apex (r5apex.exe)** usage time

https://store.steampowered.com/app/1172470

## To Reproduce

1. "ActivityWatch" is launching at startup
2. Run "Apex (r5apex.exe)"
3. Open Dashboard
4. Click "Activity" or "Timeline"
5. "Activity" > No record of **r5apex.exe** appears
6. "Timeline" > A blank segment appears

## Expected behavior

"Activity" & "Timeline" > A record of **r5apex.exe** appears

## Documentation

![图片](https://github.com/ActivityWatch/activitywatch/assets/45323123/15e51ee4-07e7-4826-9af5-e76bcedc0e14)

**Comment by BelKed** [comment] 2024-01-03 15:44
Possible duplicate of https://github.com/ActivityWatch/activitywatch/issues/873

**Comment by suiahae** [comment] 2024-01-03 16:19
> Possible duplicate of #873

Thanks for your tip, I tried the methods mentioned in #873, both of which **can solve** this problem: 

- Run ActivityWatch (aw-qt.exe) with administrator privileges
- Roll back to v0.12.1 

The only difference is that Apex (r5apex.exe ) is a  **Steam game**  and is **same not running** under administrator privileges.

**Comment by ErikBjare** [comment] 2024-01-05 11:48
Thanks for testing it @suiahae!

Might be bold and merge this without testing it myself. Goal is to get a new beta release out that fixes this ASAP (along with another window watcher fix for macOS).

**Closed** 2024-01-05 16:05 UTC
Labels: type: bug
