### ISSUE TITLE
When trying to modify some settings: TypeError: Cannot read properties of undefined (reading 'value').

### ISSUE THREAD

**Issue by GitPinkRabbit** [ActivityWatch/activitywatch#746] opened 2022-06-10 17:05 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11 Home Version 21H2, OS build 22000.675, Windows Feature Experience Pack 1000.22000.675.0
- **ActivityWatch version**: v0.11.0

## Describe the bug

In Settings (/#/settings), when I try to modify the `Duration default value`, an error occurs:

> TypeError: Cannot read properties of undefined (reading 'value'). See dev console (F12) and/or server logs for more info.

Console:

```
TypeError: Cannot read properties of undefined (reading 'value')
    at change (TimelineDurationSettings.vue:1:329)
    at ne (es.object.is.js:1854:26)
    at a.n (es.object.is.js:2179:14)
    at ne (es.object.is.js:1854:26)
    at Cn.t.$emit (es.object.is.js:3888:9)
    at a.<anonymous> (form-spinbutton.js:83:15)
    at Array.<anonymous> (es.object.is.js:1980:12)
    at ce (es.object.is.js:1906:12)
```

## To Reproduce

'Settings' -> change 'Duration default value'

## Documentation

A screenshot:

![](https://user-images.githubusercontent.com/46786295/173116161-f554d17b-a9bd-45a4-899f-42fc90541aed.png)

**Comment by BelKed** [comment] 2022-06-11 13:33
I can't reproduce this issue on the latest beta (`v0.12.0b2`) on macOS High Sierra 10.13.6.
If I remember correctly, I think I had the same problem with the older version, but upgrading solved it...

**Comment by elhadouki** [comment] 2022-06-12 23:38
I have the same issue on linux mint!
ActivityWatch Version: v0.11.0
Error:
**TypeError: Cannot read properties of undefined (reading 'value'). See dev console (F12) and/or server logs for more info.**
console:
```
TypeError: Cannot read properties of undefined (reading 'value')
    at change (DaystartSettings.vue?8b7c:1:327)
    at ne (es.object.is.js:1854:26)
    at a.n (es.object.is.js:2179:14)
    at ne (es.object.is.js:1854:26)
    at Cn.t.$emit (es.object.is.js:3888:9)
    at a.onChange (form-validity.js:228:12)
    at ne (es.object.is.js:1854:26)
    at HTMLInputElement.n (es.object.is.js:2179:14)
    at Ji.o._wrapper (es.object.is.js:6917:25)
```

**Comment by ErikBjare** [comment] 2022-06-13 14:57
This has been reported a half-dozen times (see https://github.com/ActivityWatch/activitywatch/issues/726#issuecomment-1118479786), and is fixed in the latest beta.

Please search more thoroughly before reporting.

**Closed by ErikBjare** 2022-06-13 14:57 UTC
Labels: type: bug, duplicate
