### ISSUE TITLE
Activity that crosses the hour mark does not appear correctly in the Activity Dashboard charts.

### ISSUE THREAD

**Issue by BillNielsenPB** [ActivityWatch/activitywatch#652] opened 2021-08-06 22:16 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10.0.19042 Build 19042
- **ActivityWatch version**: v0.11.0

## Describe the bug
This issue can be best observed using long sections of active time ("not-afk") which will not appear in charts filtered with "Exclude AFK time". But I am willing to bet this happens with other watchers too.

## To Reproduce
1. Log over an hour of uninterrupted non-afk time.
2. Go to the activity dashboard.
3. Add a bar chart to make the issue more visible.
4. Notice the section of active time is missing from the bar chart.
5. Open the Filter menu.
6. Uncheck "Exclude AFK time"
7. Observe, the recorded 1hr+ of non-afk does not appear in the bar chart.

## Expected behavior
Exclude AFK time does not filter out long sections of active non-afk time.

## Documentation
Exclude AFK time:
![image](https://user-images.githubusercontent.com/62147699/128574629-67a23cf2-2b91-4be0-9d9f-85ee96f0081e.png)

Unchecked:
![image](https://user-images.githubusercontent.com/62147699/128574680-27a2e6f0-0ad1-47a7-9830-48e50bb075a6.png)

Timeline:
![image](https://user-images.githubusercontent.com/62147699/128574747-d0e1a60a-7e33-4a5a-b7f3-68f3d0889ab0.png)

##Additional Context
This can be worked around by manually splitting the "non-afk" time at the hour marks.

**Comment by ErikBjare** [comment] 2021-08-18 10:03
There's a merged fix for this in aw-core master (https://github.com/ActivityWatch/aw-core/pull/102/files).

Unfortunately, it comes with a pretty bad performance hit, but we'll probably ship it in the next version anyway.

aw-server-rust is unaffected.

**Comment by ErikBjare** [comment] 2021-10-06 07:54
Fixed in master and duplicate of #609

Closing.

**Closed by ErikBjare** 2021-10-06 07:54 UTC
Labels: type: bug
