### ISSUE TITLE
"Module aw-watcher-window quit unexpectedly."

### ISSUE THREAD

**Issue by schackbrian2012** [ActivityWatch/activitywatch#918] opened 2023-07-11 15:34 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**:  macOS Big Sur Version 11.2.3
- **ActivityWatch version**:  v0.12.2

## Describe the bug

I use the [ActivityWatch app](https://activitywatch.net/) to track the time that I spend on the computer. I am running v0.12.2 which is the latest version. When I restart the computer, it displays an error message. The error message says, "Module aw-watcher-window quit unexpectedly." It has three buttons: Hide Details..., Cancel, and Restart. The details pane says the following:

```
2023-07-03 12:33:23 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-07-03 12:33:24 [INFO ]: Using swift strategy, calling out to swift binary  (aw_watcher_window.main:67)
2023-07-03 12:33:24 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
```

I searched in [the documentation](https://docs.activitywatch.net/en/latest/search.html?q=module+aw-watcher-window+quit+unexpectedly), but I did not find this error message. I asked about this issue on [the Ask Different website](https://apple.stackexchange.com/questions/460802/module-aw-watcher-window-quit-unexpectedly) from the Stack Exchange network, and the comments referred me to contact the developer. I found a related issue on GitHub ["AW crashed unexpectedly after BSOD"](https://github.com/ActivityWatch/activitywatch/issues/297). That issue occurs on Windows, and my issue occurs on macOS. I tried the solution for that issue –– deleting the Application Support folder –– but that did not work.

How can I prevent this error from occurring? Please find attached [a screenshot of the error message](https://i.stack.imgur.com/IFknr.png).

## To Reproduce

Restart the computer.

## Expected behavior

No error message.

## Documentation

Please find attached a [screenshot of the error message](https://i.stack.imgur.com/IFknr.png). The log file at ~/Library/Logs/activitywatch/aw-watcher-window/aw-watcher-window_2023-07-11T10-47-27.log says:

```
2023-07-11 10:47:27 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-07-11 10:47:28 [INFO ]: Using swift strategy, calling out to swift binary  (aw_watcher_window.main:67)
2023-07-11 10:47:28 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
```

**Comment by BelKed** [comment] 2023-07-12 13:23
I can also confirm that this problem occurs on my Mac, but only when my computer crashes (usually when it runs out of RAM because 8 GB is not enough).

The cause is probably the same as in the Windows issue — ActivityWatch doesn't quit properly, and on reboot when the application starts it can't because the instance of ActivityWatch from before the reboot is still/already running.

If it happens next time, you could manually force quit the running processes of ActivityWatch in the Activity Monitor app, and launch it normally from the Applications folder.

<img width="842" alt="Screenshot 2023-07-12 at 15 21 33" src="https://github.com/ActivityWatch/activitywatch/assets/66956532/c5437cfc-ce2b-42cc-aa5e-b7d12ca3bb33">

**Comment by schackbrian2012** [comment] 2023-07-12 15:22
@BelKed Thank you for your interest in helping with this issue. I checked under Apple menu –> About This Mac, and I have 16 GB of memory. You said, "[T]he instance of ActivityWatch from before the reboot is still/already running." I don't understand this. I thought that rebooting would quit everything. How could ActivityWatch still be running? I tried following your instructions. I force quit ActivityWatch in Activity Monitor. Then I relaunched ActivityWatch. Unfortunately, the Activity view shows, "No data." I can wait to see whether the data takes some time to accumulate.

**Comment by BelKed** [comment] 2023-07-12 22:53
> I thought that rebooting would quit everything.

If you leave the `Reopen windows when logging back in` checkbox checked, the system will save every single application that is currently running so that it can shut itself down. Then, when you reboot, it will reopen windows that were open before you rebooted. At least, that's how I think it works :)

<p align=center>
<img width="400" alt="Screenshot" src="https://github.com/ActivityWatch/activitywatch/assets/66956532/3f1dc2f6-dbf9-4841-8238-53c2609444ad">
</p>

ActivityWatch is probably saved as the application that was running before you rebooted. And if ActivityWatch is set as the application to open on login (which is the default, if I'm right), this would be a second instance of ActivityWatch running. When it tries to launch, it crashes with `Module aw-watcher-window quit unexpectedly`.

So could you try restarting with the `Reopen windows when logging back in` checkbox unchecked?

<p align=center>
<img width="400" alt="Screenshot" src="https://github.com/ActivityWatch/activitywatch/assets/66956532/2d732ffc-ff27-4b91-b96c-94b17afa3b1e">
</p>

---

> Unfortunately, the Activity view shows, "No data."

Then, please check if the ActivityWatch modules are running — a checkmark will appear in front of the module name if it's running. I'm using `aw-server-rust` as the ActivityWatch server. If you're using the default Python server, you should have a checkmark in front of `aw-server`.

<p align=center>
<img width="400" alt="Screenshot" src="https://github.com/ActivityWatch/activitywatch/assets/66956532/d78c6222-a484-4648-b54a-ef9e34a688f2">
</p>

**Comment by BelKed** [comment] 2023-07-12 23:01
Thinking deeply about it now, maybe you have ActivityWatch twice in your `Login Items`, maybe as two separate versions or something...

<p align=center>
<img width="600" alt="Screenshot" src="https://github.com/ActivityWatch/activitywatch/assets/66956532/e38ad4fe-ceb6-4c6e-94b3-691185cdd221">
</p>

**Comment by schackbrian2012** [comment] 2023-07-25 15:53
@BelKed I have been traveling overseas without Internet service, so I could not reply to your message earlier. I will try the troubleshooting ideas that you suggested.

**Comment by tomzx** [comment] 2023-07-25 17:55
Running `aw-watcher-window` on BigSur 11.7.8 results in the following output:
```
2023-07-25 13:07:51 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
usage: aw-watcher-window [-h] [--host HOST] [--port PORT] [--testing] [--exclude-title] [--verbose] [--poll-time POLL_TIME] [--strategy {jxa,applescript,swift}]
aw-watcher-window: error: unrecognized arguments: -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
usage: aw-watcher-window [-h] [--host HOST] [--port PORT] [--testing] [--exclude-title] [--verbose] [--poll-time POLL_TIME] [--strategy {jxa,applescript,swift}]
aw-watcher-window: error: unrecognized arguments: --multiprocessing-fork tracker_fd=6 pipe_handle=8
2023-07-25 13:07:52 [INFO ]: Using swift strategy, calling out to swift binary  (aw_watcher_window.main:67)
dyld: Library not loaded: /usr/lib/swift/libswift_Concurrency.dylib
  Referenced from: /Applications/ActivityWatch.app/Contents/MacOS/aw_watcher_window/aw-watcher-window-macos
  Reason: image not found
2023-07-25 13:07:52 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
```
The file `/usr/lib/swift/libswift_Concurrency.dylib` does not exist. After a bit of search, it appears that `libswift_Concurrency.dylib` is available with XCode 13 and/or MacOS 12.

**Comment by BelKed** [comment] 2023-07-25 20:05
@tomzx There is already an open [issue](https://github.com/ActivityWatch/activitywatch/issues/801) for the problem you mention :)

**Comment by schackbrian2012** [comment] 2023-07-25 20:50
Rebooting: Using Command-Tab, Command-W, and Command-Q, I closed the open windows and applications. Then under Apple menu –> Restart..., I unchecked "Reopen windows when logging back in," and clicked the Restart button.

aw-server: Under ActivityWatch menu –> Modules, the aw-server menu item is checked.

Login Items: Under Apple menu –> System Preferences... –> Users & Groups –> Login Items, I removed and re-added ActivityWatch from the Applications folder.

Unfortunately, I am still getting the error message and no data.

**Comment by BelKed** [comment] 2023-07-26 08:14
Okay, I can think of one more thing. (No idea why I didn't start with that...)

Could you please try to run the `aw-watcher-window` from the **Terminal** using the following command?

```
/Applications/ActivityWatch.app/Contents/MacOS/aw-watcher-window
```

This should tell us exactly what is causing the problem.

And then please restart your computer and try to run it again from **Terminal** after the error message pops up :)

**Comment by schackbrian2012** [comment] 2023-08-05 21:07
@BelKed I ran aw-watcher-window from the Terminal as you suggested, and I got the following error:

```
% /Applications/ActivityWatch.app/Contents/MacOS/aw-watcher-window
2023-08-05 17:04:23 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
usage: aw-watcher-window [-h] [--host HOST] [--port PORT] [--testing]
                         [--exclude-title] [--verbose] [--poll-time POLL_TIME]
                         [--strategy {jxa,applescript,swift}]
aw-watcher-window: error: unrecognized arguments: --multiprocessing-fork tracker_fd=6 pipe_handle=8
usage: aw-watcher-window [-h] [--host HOST] [--port PORT] [--testing]
                         [--exclude-title] [--verbose] [--poll-time POLL_TIME]
                         [--strategy {jxa,applescript,swift}]
aw-watcher-window: error: unrecognized arguments: -B -S -E -s -c from multiprocessing.resource_tracker import main;main(5)
2023-08-05 17:04:24 [INFO ]: Using swift strategy, calling out to swift binary  (aw_watcher_window.main:67)
dyld: Library not loaded: /usr/lib/swift/libswift_Concurrency.dylib
  Referenced from: /Applications/ActivityWatch.app/Contents/MacOS/aw_watcher_window/aw-watcher-window-macos
  Reason: image not found
2023-08-05 17:04:24 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
```

**Comment by BelKed** [comment] 2023-08-06 09:21
Okay, so the problem is the same as in https://github.com/ActivityWatch/activitywatch/issues/801.
Could you please close this issue, since it's a duplicate of the mentioned one? :)

**Comment by schackbrian2012** [comment] 2023-08-06 16:04
As advised by @BelKed, I am closing this issue as a duplicate of ["dyld: Library not loaded: /usr/lib/swift/libswift_Concurrency.dylib on v0.12.1 for macOS 11.6."](https://github.com/ActivityWatch/activitywatch/issues/801)

**Closed** 2023-08-06 16:04 UTC
Labels: type: bug

**Comment by BelKed** [comment] 2023-08-12 08:28
You are facing exactly the same issue :)

The easiest workaround I can think of is to install an older version of ActivityWatch.
Or install the latest version and use the `aw-watcher-window` from the older version.

Anyways, if you have any other questions regarding this issue, please write them here: https://github.com/ActivityWatch/activitywatch/issues/801
