### ISSUE TITLE
[Mac] “ActivityWatch.app“ wants access to control “System Events.app“ dialog shows up repeatedly

### ISSUE THREAD

**Issue by ChaitanyaPramod** [ActivityWatch/activitywatch#419] opened 2020-04-21 10:15 UTC
## Describe the bug
[Mac] “ActivityWatch.app“ wants access to control “System Events.app“ dialog shows up repeatedly

## To Reproduce
1. Install AcitivityWatch with `homebrew cask install activitywatch`
2. Start ActivityWatch.app
3. Wait a few minutes
4. Dialog asking "“ActivityWatch.app“ wants access to control “System Events.app“" shows up repeatedly every few minutes even after allowing

## Expected behavior
Dialog should not show up again after allowing

## Documentation
Dialog in question:
<img width="532" alt="Screen Shot 2020-04-21 at 3 29 25 PM" src="https://user-images.githubusercontent.com/692546/79854110-94c6e180-83e6-11ea-9da8-5d49447ad70f.png">

Logfiles: (nothing relevant found, sharing anyway) 
[logs.zip](https://github.com/ActivityWatch/activitywatch/files/4509246/logs.zip)

## Environment
 - ActivityWatch version: v0.9.2
 - OS: macOS 10.14.6 (Mojave)

## Additional context
- Another user's report on Stack Exchange: https://apple.stackexchange.com/q/385104 . I did not follow the recommended answer as I did not want to move the .app ownership to root user.
- Disallowing and then allowing access from System Preferences > Security & Privacy > Privacy > Automation did not change behavior

**Comment by ErikBjare** [comment] 2020-04-21 10:21
Thanks for the detailed report, but it is a duplicate of https://github.com/ActivityWatch/activitywatch/issues/380

Closing.

**Closed** 2020-04-21 10:21 UTC
Labels: duplicate
