### ISSUE TITLE
Stopwatch edit: wrong entry in popup

### ISSUE THREAD

**Issue by mrkeuz** [ActivityWatch/activitywatch#565] opened 2021-02-13 12:16 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 20.04.2 + Chrome 88.0.4324.150 (latest)
- **ActivityWatch version**: Version: v0.10.0

## Describe the bug

When I have tried to edit history entry popup show me OTHER entry to edit (see screenshots) 

## To Reproduce

  Steps to reproduce the behavior, for example:
    1. Go to 'Stopwatch' page
    2. Edit last history entry 
    3. Save entry
    4. Start new timer 
    5. Stop timer
    6. Click on 'Edit' on last entry in history (for last timer)
    7. Label in popup is wrong 
    8. Edit and save entry
    9. All saves will go to wrong entry (although ID and date seems valid on screen)

Screenshots
![aw-stopwatch-edit](https://user-images.githubusercontent.com/6247921/107849515-be854500-6e0c-11eb-8d71-d6e3c7ad92a4.png)

## Expected behavior

1. Valid entry name
2. Save data into correct entry

## Documentation
N/A
## Additional context
N/A

**Comment by johan-bjareholt** [comment] 2021-02-13 17:41
This looks like a duplicate of https://github.com/ActivityWatch/activitywatch/issues/524

This has been fixed on the master branch, so it should work on the next release https://github.com/ActivityWatch/aw-webui/pull/242

**Closed by johan-bjareholt** 2021-02-13 17:41 UTC
Labels: type: bug

**Comment by mrkeuz** [comment] 2021-02-13 17:55
Cool! Sorry, did not find this ticket by some reason. Will try to test on nightly builds (just found it). Thanks!

**Comment by johan-bjareholt** [comment] 2021-02-13 18:06
No problem, it's not easy to find.
Hopefully in the future we will also make releases more often, lowering the risk of this occuring.
