### ISSUE TITLE
The app is closed after opened

### ISSUE THREAD

**Issue by EKF0** [ActivityWatch/activitywatch#1108] opened 2024-10-23 17:56 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- **ActivityWatch version**: 

## Describe the bug

On my andriod app the app keep closed after opened and scroll a little

**Comment by brayo-pip** [comment] 2024-10-24 12:15
Is it still happening?

**Comment by ErikBjare** [comment] 2024-10-24 15:36
Without logs there is nothing we can do about this. Likely to be a duplicate of another open issue.

**Closed by ErikBjare** 2024-10-24 15:36 UTC
Labels: type: bug

**Comment by EKF0** [comment] 2024-10-24 20:08
Thank you, It works now well after one day from install on my andriod

**Comment by brayo-pip** [comment] 2024-10-24 20:46
Tends to happen on new installs.
