### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value'). See dev console (F12) and/or server logs for more info.

### ISSUE THREAD

**Issue by cold911** [ActivityWatch/activitywatch#726] opened 2022-04-06 07:48 UTC
TypeError: Cannot read properties of undefined (reading 'value'). See dev console (F12) and/or server logs for more info.

- **OS name and version**: Manjaro 21.2.5
- **ActivityWatch version**: aur/activitywatch-bin 0.11.0-3 (+29 1.12) (Installed) webUI Version: v0.11.0

## Describe the bug
error after saving settings in browser

## To Reproduce

**Browser console**
```
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
3
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'value')
    at change (LandingPageSettings.vue?f8a9:1:344)
    at ne (vue.runtime.esm.js:1854:26)
    at a.n (vue.runtime.esm.js:2179:14)
    at ne (vue.runtime.esm.js:1854:26)
    at a.Cn.t.$emit (vue.runtime.esm.js:3888:9)
    at a.<anonymous> (form-select.js:83:15)
    at Array.<anonymous> (vue.runtime.esm.js:1980:12)
    at ce (vue.runtime.esm.js:1906:12)
```
﻿
![aw-bug](https://user-images.githubusercontent.com/6339180/161922994-fe0c25dd-c289-4d8a-9889-4083370414b0.jpg)

Thanks

**Comment by yukimuon** [comment] 2022-05-01 04:58
Same bug here, on Windows 11 Chrome

**Comment by ErikBjare** [comment] 2022-05-05 12:17
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/681, https://github.com/ActivityWatch/activitywatch/issues/685, https://github.com/ActivityWatch/activitywatch/issues/697, https://github.com/ActivityWatch/activitywatch/issues/716

Fixed in master, will work correctly in the next release.

**Closed by ErikBjare** 2022-05-05 12:17 UTC
Labels: type: bug

**Comment by ErikBjare** [comment] 2022-06-30 13:54
@dennys That looks like a different issue.

If you think it's a bug and not just a configuration issue (see https://docs.activitywatch.net/en/latest/remote-server.html) then please open a new issue, thanks!
