### ISSUE TITLE
Timezone seems to be off by 2 hours

### ISSUE THREAD

**Issue by WouterGordts** [ActivityWatch/activitywatch#90] opened 2017-07-27 19:39 UTC
On my debian stretch install the web gui timestamps seem to be two hours off from my local time. My timezone is Brussels if this would help. The timestamps in the .cache/activitywatch/log seem to be the correct time though.

**Comment by ErikBjare** [comment] 2017-07-28 10:04
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/72, thanks for reporting!

**Closed by ErikBjare** 2017-07-28 10:04 UTC
