### ISSUE TITLE
Support private mode

### ISSUE THREAD

**Issue by Rapiz1** [ActivityWatch/activitywatch#330] opened 2020-01-05 01:49 UTC
**Is your feature request related to a problem? Please describe.**
Browsers have private mode so that they won't record users' activity. Domains can be untracked by disabling the ActivityWatch plugin. However, windows titles will still be recorded.

**Describe the solution you'd like**
I think it may be useful if we can have string match patterns like categories to make some application untracked.

**Describe alternatives you've considered**
Users may modify their raw data by scripts to delete the history they don't want. But I have failed to locate the files.

**Comment by johan-bjareholt** [comment] 2020-01-05 17:44
Good point.

There's a quick and dirty fix to run aw-watcher-window in a "private" mode which makes it still run and send appname but always has the appid set to "excluded". That's definitely not a proper solution though, but we've had things like this in mind for the future.

Good idea that we could exclude it if it matches a pattern similar to how the categorization works, in contrast to how our current private mode for aw-watcher-window works though we should probably hide both window title as well as appid since someone might have a different use-case than just icognito.

We should probably put this on the forum so it can be prioritized.

**Comment by johan-bjareholt** [comment] 2020-01-05 17:46
Oh, just found that there already is and you've already commented on it

https://forum.activitywatch.net/t/add-an-exclude-list/345/

Your use-case is different, but otherwise the feature in itself is the same I guess.

**Comment by johan-bjareholt** [comment] 2020-03-01 15:07
This is also a duplicate of https://github.com/ActivityWatch/activitywatch/issues/1

closing

**Closed by johan-bjareholt** 2020-03-01 15:07 UTC
