### ISSUE TITLE
Cannot start stopwatch on Win10

### ISSUE THREAD

**Issue by ProfessorX** [ActivityWatch/activitywatch#692] opened 2021-12-14 01:50 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- MS Windows 10.0.19044.1387
- **ActivityWatch version**: 

## Describe the bug

I cannot start the stopwatch.

## To Reproduce

    1. Go to stopwatch
    2. Click on add stopwatch name

    3. Click satrt
  ![cannot-start-stopwatch](https://user-images.githubusercontent.com/1704352/145917960-7a4e3968-0114-46a2-8cb1-a0739b712ffa.png)

![Snipaste_2021-12-14_09-49-51](https://user-images.githubusercontent.com/1704352/145918133-51a5f92f-3289-4179-a69e-029091a08a6e.png)

TypeError: Cannot read properties of null (reading 'timestamp'). See dev console (F12) and/or server logs for more info.

## Expected behavior

Normal behavior. 

I can understand since the APP is under dev.

## Documentation

[aw-server_2021-12-14T09-34-20.log](https://github.com/ActivityWatch/activitywatch/files/7708062/aw-server_2021-12-14T09-34-20.log)

**Comment by mrprints** [comment] 2022-01-06 21:11
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
- [x] I have searched the issues of this repo and believe that my issue is generally a duplicate of the bug I'm commenting on [#692](https://github.com/ActivityWatch/activitywatch/issues/692), but I am encountering a slightly different error message and, thus, have additional info to share.

TypeError: t is null. See dev console (F12) and/or server logs for more info.

I'm not sure what, if any, part of my server logs I should upload so I'm just pasting browser screenshots for now
![activitywatch-stopwatch-defect](https://user-images.githubusercontent.com/64180256/148452374-9ae588af-debd-4639-b502-6fb9a0e8c7a5.png)
![activitywatch-stopwatch-defect-log](https://user-images.githubusercontent.com/64180256/148452398-c41464dd-f16e-4e7e-9f1d-ccd7d129769d.png)

**Comment by nicolae-stroncea** [comment] 2022-03-22 19:26
I have the same issue as @mrprints  on my Linux machine. If I start a new event in the stopwatch it, I will get the TypeError and the UI will not update. Once I refresh the page, I will see a new event in the stopwatch so the action went through successfully, but there's still some sort of weird error that breaks the UI

**Comment by ErikBjare** [comment] 2022-04-15 14:11
Duplicate of #615, fixed and will work in the next release.

**Closed** 2022-04-15 14:12 UTC
Labels: type: bug
