### ISSUE TITLE
TypeError: t is undefined. See dev console (F12) and/or server logs for more info.

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#634] opened 2021-07-08 10:37 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

- **Windows 10**: 
- **ActivityWatch 0.11**: 

## Describe the bug

TypeError: t is undefined. See dev console (F12) and/or server logs for more info.

+ Ugly presentation (too thin letters - previous version was better).

## Additional context

![obraz](https://user-images.githubusercontent.com/1080880/124907980-1a817d80-dfe9-11eb-856b-389879419053.png)
TypeError: t is undefined
    datasets TimelineBarChart.vue:99
    Lodash 10
        o
        n
        d
        o
        i
        o
        h
        s
        n
        o
    value TimelineBarChart.vue:99
    value TimelineBarChart.vue:50
    VueJS 4
        run
        Kn
        pe
        ce
vue.runtime.esm.js:1888:12

**Comment by ErikBjare** [comment] 2021-07-08 13:27
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/612

**Closed by ErikBjare** 2021-07-08 13:27 UTC
Labels: type: bug
