### ISSUE TITLE
Receiving frequent query timeouts caused by frequent window title changes

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#217] opened 2018-08-03 19:46 UTC
I've been getting an increasing amount of timeouts with the message:

Console:   

```
Mounting aw-periodusage PeriodUsage.vue:26
Mounting aw-summary
Summary.vue:22
Mounting aw-timeline TimelineInspect.vue:22
Mounting aw-sunburst Sunburst.vue:118
Mounting aw-timeline TimelineInspect.vue:22
Mounting aw-summary
Summary.vue:22
Error: "timeout of 10000ms exceeded"
exportshttp://localhost:5600/static/js/0.f288d34cc371f7d2215c.js:40:248389
ontimeouthttp://localhost:5600/static/js/0.f288d34cc371f7d2215c.js:40:249607
errorHandler Activity.vue:357
```

Identical issue is happening in both Chrome and Firefox. For the past hour, i've not been able to view my data because of it.

**Comment by ErikBjare** [comment] 2018-08-06 17:52
I'm assuming this has to do with the queries taking too long to run. Do you have a fast computer? How many events do you have in your buckets?

**Comment by nicolae-stroncea** [comment] 2018-08-11 11:15
My computer is fairly fast. The main issue was the number of events logged in

**Comment by ErikBjare** [comment] 2018-08-11 18:55
@nicolae-stroncea Please tell us the number of events you have in each bucket.

It really shouldn't take more than 10 seconds, perhaps you have a window title that changes unusually many times in a day? That could significantly slow down the calculation.

**Comment by nicolae-stroncea** [comment] 2018-08-11 19:09
@ErikBjare  how do I find the number of events in each bucket for the specific day?

**Comment by ErikBjare** [comment] 2018-08-13 12:19
Ah yes, having the window title change like that is likely the cause if the issue. I'm not sure if there's a good workaround though (apart from improving query performance), what do you think @johan-bjareholt? (He won't reply in a couple of weeks as he's on vacation, unfortunately)

**Comment by ErikBjare** [comment] 2020-02-15 15:11
This should not be a problem in the latest release which has much improved queries. Closing.

**Closed by ErikBjare** 2020-02-15 15:11 UTC
Labels: improves: performance, priority: low, type: bug
