### ISSUE TITLE
Netflix in Fullscreen

### ISSUE THREAD

**Issue by Bl4ckspell7** [ActivityWatch/activitywatch#560] opened 2021-02-07 15:02 UTC
Netflix in browser in full screen is not recognized

**Comment by ErikBjare** [comment] 2021-02-07 16:11
This is most likely due to you not using your mouse/keyboard while watching Netflix. Therefore a duplicate of https://github.com/ActivityWatch/activitywatch/issues/261.

Closing.

**Closed by ErikBjare** 2021-02-07 16:11 UTC
Labels: duplicate
