### ISSUE TITLE
Sunburst clock can't show the whole 24-hour-event when 'start of day' in settings set anyvalue except 00:00

### ISSUE THREAD

**Issue by szh-bash** [ActivityWatch/activitywatch#875] opened 2023-04-30 05:55 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: win11-22h2 pro
- **ActivityWatch version**: 0.4.3

## Describe the bug
It seems like AW choose to show the event between 'start of day' and midnight(24:00) in Sunburst clock which can be choosen to display in Summary. 

I think it would be better if it could show [start, start+24h) as we do in live 24 hours a day, right?

## To Reproduce

1. Go to settings
2. Set 'start of day' any value except 00:00, such as 04:00
![image](https://user-images.githubusercontent.com/27895812/235337900-e39972ad-d5ec-4744-b551-43748464b3ce.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/27895812/235337813-583b8476-30a0-498e-8e36-5a512e5cd0e3.png)

**Comment by szh-bash** [comment] 2023-04-30 06:00
https://github.com/ActivityWatch/activitywatch/issues/508#issuecomment-753478789 it seems like 0:00 bug still exists so far @ErikBjare

**Comment by BelKed** [comment] 2023-04-30 07:28
If the bug still exists, why are you opening a duplicate issue?

**Comment by szh-bash** [comment] 2023-04-30 07:36
> opening a duplicate issue?

I don't get it. If you were asking why i opened this issue, I found all the other relevant issue in this repo closed so i make a new one

**Comment by BelKed** [comment] 2023-04-30 07:45
Oh, sorry, my bad...

I've thought the issue you mentioned was open.
GitHub app doesn't have that much clear UI...

But, there still exists an opened issue: https://github.com/ActivityWatch/aw-webui/issues/358

**Comment by szh-bash** [comment] 2023-04-30 08:28
> Oh, sorry, my bad...
> 
> I've thought the issue you mentioned was open. GitHub app doesn't have that much clear UI...
> 
> But, there still exists an opened issue: [ActivityWatch/aw-webui#358](https://github.com/ActivityWatch/aw-webui/issues/358)

you reopened it 44mins ago, i post this issue 2hours ago...nvm, just forget about it

**Comment by BelKed** [comment] 2023-04-30 08:32
I closed it because I thought the mentioned issue was opened, so mine would also be a duplicate.
And, when you've written that the issue isn't opened, I've also reopened mine.

**Comment by szh-bash** [comment] 2023-04-30 08:39
> I closed it because I thought the mentioned issue was opened, so mine would also be a duplicate. And, when you've written that the issue isn't opened, I've also reopened mine.

Sorry i misread and i didn't think about searching issues in other repos so didn't find yours at first.

But it's already 8 months, maybe it's time to post this new issue?

**Comment by BelKed** [comment] 2023-04-30 08:43
That's fine :)

And I highly doubt that opening another issue would speed up the process of fixing the problem :D
But feel free to do what you think is right :)

**Closed** 2023-11-25 06:10 UTC
Labels: type: bug
