### ISSUE TITLE
Clock view doesn't show acitivity after midgnight

### ISSUE THREAD

**Issue by sojusnik** [ActivityWatch/activitywatch#510] opened 2020-11-19 09:55 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 20.04
- **ActivityWatch version**: v0.9.2

## Describe the bug

The activity indicator stops at midnight in the clock view, although the activity itself goes beyond midnight, as shown in the inserted picture.

## Expected behavior

The green "not-afk" indicator should show the whole activity time and not stop at midnight.

## Documentation

![watch](https://user-images.githubusercontent.com/1245718/99649988-28cc5a80-2a55-11eb-802d-5c60719cf98a.png)

**Comment by ErikBjare** [comment] 2020-11-19 10:02
Duplicate of #508, closing.

**Closed by ErikBjare** 2020-11-19 10:03 UTC
Labels: type: bug
