### ISSUE TITLE
Bitdefender aw-qt.exe Act4.Detection

### ISSUE THREAD

**Issue by Astuceman** [ActivityWatch/activitywatch#310] opened 2019-11-13 18:36 UTC
## Describe the bug
It's not a bug.
Bitdefender act like it's some type of virus (i know it's not the case)

## To Reproduce
Simply launch aw-qt.exe

## Expected behavior
It place aw-qt.exe in quarantine

## Documentation
![Capture](https://user-images.githubusercontent.com/19632209/68793309-42baac80-064d-11ea-8628-2c6c14b87535.PNG)

Logfiles can be found in different places depending on platform:
 - Windows: `C:\Users\<USER>\AppData\Local\ActivityWatch\Logs`
 - macOS: /Users/<USER>/Library/Logs/activitywatch
 - Linux: /home/<USER>/.cache/SuperApp/log

## Environment
 - ActivityWatch version: [e.g. v0.8.2]
 - OS: [Windows 10 1903]

**Comment by ErikBjare** [comment] 2019-11-13 18:57
This is a false positive, and it happens with practically every new version we release until the anti-virus vendors learn that it isn't.

Unfortunately, v0.8.2 appears to be broken (I thought I had fixed the issue with v0.8.1, but it appears there is another issue...).

**Comment by Cristy94** [comment] 2019-11-15 21:56
Also VirusTotal shows some Adware: https://www.virustotal.com/gui/file/010e7bb5e275b48914e980fa5b80b0ad101ff878bafb75d6275169945998702d/detection

**Comment by ErikBjare** [comment] 2019-12-02 16:23
Kind of a duplicate of #181, closing.

**Closed by ErikBjare** 2019-12-02 16:23 UTC
Labels: duplicate
