### ISSUE TITLE
Idea: ML classifier for projects

### ISSUE THREAD

**Issue by staltz** [ActivityWatch/activitywatch#191] opened 2018-05-08 09:29 UTC
Having migrated from [Timing](https://timingapp.com/) (macOS) to AW (Linux, at the moment), the one thing I miss most is the classifier for events. You set some rules (some if-else conditions in the app), and then it automatically detects those cases and creates a "project event" based on the raw events.

As an idea, someone could build a watcher for activitywatch which looks at raw events and looks at the project classification set manually by the user, then learns over time how to classify. This looks like a typical use case for supervised machine learning. Timingapp (as far as I know) is not that sophisticated, it seems like it employs a basic decision tree algorithm, but activitywatch could go further and apply some statistical machine learning.

**Comment by johan-bjareholt** [comment] 2018-05-08 13:45
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/95 but with some new ideas such as adding more sophisticated algorithms for the tagging such as supervised machine learning. Closing this, let's keep the discussion in a single issue.

**Closed by johan-bjareholt** 2018-05-08 13:45 UTC
