### ISSUE TITLE
Slow UI and timeouts `30000ms` on weekly/multi-day reports

### ISSUE THREAD

**Issue by mrkeuz** [ActivityWatch/activitywatch#701] opened 2022-01-05 11:27 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
`Linux ubnt 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- **ActivityWatch version**: 
     v0.11.0

## Describe the bug
Time to time UI show next error for long period reports:

`Error: timeout of 30000ms exceeded. See dev console (F12) and/or server logs for more info.` (see Screenshot)

As on "Activity" tab, but also on "Timeline" tabs. Issue reproduces sometime on daily reports and also on date range reports.

## To Reproduce
1. Several months history
2. Go to e.g. to Timeline tab
3. Select multi-day report
* Also, maybe queries to database "stacked", as I was clicking numerous times to needed period. Don't sure. Issue is not reproducing sometimes.

## Expected behavior

- Long but durable reports from database
- It would be good to speedup reports. Even daily `12h`/`24h` `Timeline`  report sometimes take more than 10 seconds to load. 

## Documentation

[aw-server_2021-12-29T03-38-57.log](https://github.com/ActivityWatch/activitywatch/files/7814330/aw-server_2021-12-29T03-38-57.log)

## Additional context

Database size: 181M peewee-sqlite.v2.db
Disk: SSD 
Ram: ~1-3Gb free usually 
(but swap enabled and activity utilized)

Think database can be loaded in memory. 

Screenshot:
![image](https://user-images.githubusercontent.com/6247921/148207103-fbee0611-1329-4d8a-8d1f-656f78670d05.png)

**Comment by ErikBjare** [comment] 2022-01-05 16:16
Huh, that's a bit slower than I'd expect. You could always try switching to aw-server-rust, which is much faster.

>Also, maybe queries to database "stacked"

This is probably true. I don't think we cancel query requests when they should be.

**Comment by yfzhao20** [comment] 2022-03-13 10:22
Same Problem! 

my OS:  Win10 21H2
version: 0.12.0 b1

I don't know how to switch to aw-server-rust. I tried to click icon in status bar and choose "aw-server-rust" but nothing happens. It is still slow. 🧐

**Comment by 8Dion8** [comment] 2022-04-06 10:03
Same issue, but after I see this once `localhost:5600` just stops working at all until a computer reboot. And even then, it might just error out again the same way for some reason

**Comment by floriangeigl** [comment] 2022-06-03 06:26
same here :/ - however, not new here. restarting activity watch for end-of-week-time-booking at least 5-10 times on fridays since months/versions (same on v11; currently running v0.12.0b2). I really love this tool, but the constant restarting is really enoying. Btw. no issues with the tracking at all - if, after some restarts, queries finally don't run into time-outs, all data is there from the entire week.

I'm also wondering what is the right way to migrate to rust? docs are not very helpful here IMHO (https://docs.activitywatch.net/en/latest/migrating.html#migrating-to-aw-server-rust) Do I need to have booth servers activated so migration starts? why is rust deactivated after restart? Why can't I reach localhost when only rust-server is activated? I have honestly no idea what steps to take for the migration and what modules need to be enabled in the end and how I can persist activated modules over restarts...plz help :)

**Comment by floriangeigl** [comment] 2022-06-08 06:45
Hi @Robproject - thanks. Just tried to make this work. Entirely delete activitywatch - removed my db, entire settings folder and also all program files/binariers/folders. Reinstalled (on winx64) - on Win I can't select what to install during the setup. Anyhow, I've configured the toml file to also auto-start rust. However, now it won't start the aw-server per default. It feels really like trial-and-error to migrate to rust properly. I wish there was some official guidance....
![image](https://user-images.githubusercontent.com/2580073/172549745-706a35b9-0a9a-45de-bca4-4774a29c554c.png)

**Comment by ErikBjare** [comment] 2022-06-08 07:26
@floriangeigl @Robproject Hey guys, sorry for the lacking documentation. I've just updated the docs to include more complete information, let me know if the issue persists! 

Docs are currently building, but should be done in a few min: https://docs.activitywatch.net/en/latest/migrating.html

And about the root cause here: I'm not sure why timeouts seem to happen more often on Windows than other platforms, but I'm working on making it configurable in the web UI, so you can override it for large reports.

**Comment by floriangeigl** [comment] 2022-06-08 11:02
awesome @ErikBjare - thank you so much.
So I did would you described - see attached my current config file. However, if I now (re-)start activity watch, I can't access the webui (waited 20min - still not available). I can only access it, if I also enable the old server module manually. I'm trying to check the logs - would the rust logs also be located in the "aw-server" log folder? cause I don't see a "aw-server-rust" folder in my "activitywatch\Logs" dir. 
![image](https://user-images.githubusercontent.com/2580073/172599584-4b8e86b5-1011-4b1f-8f64-d75dfe381148.png)
![image](https://user-images.githubusercontent.com/2580073/172599703-27adf0c4-0b0a-4749-9c8d-554ede5f26af.png)
![image](https://user-images.githubusercontent.com/2580073/172599751-9dddd0c1-5adb-42ba-9323-3c7c7e0f0387.png)

About the large reports - I wouldn't consider mine as large... I usually query one day ( so day per day) of the last week and still very frequently run into 30sec timeouts - on average I'm running more often in these timeouts than not running into them.

Thanks for all your help here - really appreciated it - as said, I love this project :)

**Comment by floriangeigl** [comment] 2022-06-08 11:10
okay - found the logs. they say that rust server is starting on localhost:5666 (instead of the :5600). I'm can finally reach the webui on localhost:5666 🎉
I think it would be awesome if this makes it also into the docs - best case, "Open dashboard" would guide me to :5666 instead of :5600 if I'm running rust :)

**Comment by floriangeigl** [comment] 2022-06-08 11:17
sorry for spamming - but it seems the other modules also don't know about the :5666 port... cause there's no data coming in... guess the other modules are trying to send data to :5600... 
So I found the toml config for the rust-server and changed the default port to 5600. now everything works as expected.
![image](https://user-images.githubusercontent.com/2580073/172603618-c7ae61ca-7628-4409-9be1-0337d4468e6b.png)

**Comment by ErikBjare** [comment] 2022-06-08 11:28
Oh, surprising that it ran off 5666! It should only do that in testing mode (if aw-qt is started with `--testing`) or if aw-server-rust is built in non-release mode.

I'll look into that. Thanks for the feedback!

**Comment by Robproject** [comment] 2022-06-08 14:09
>  on Win I can't select what to install during the setup. 

Sorry - clarification - I meant selecting the server under modules when right clicking activity watch in the tray. When it was running like normal with a check next to aw-server but not aw-server-rust, clicking aw-server deselected it and so nothing was running. Then clicking aw-server-rust allowed it to work as intended, and it took some time to migrate the db. After that, python would still start by default so changed config.

**Comment by ErikBjare** [comment] 2022-06-08 15:50
@johan-bjareholt While it might be confusing, no data is actually lost, it just takes some effort to consolidate again (which will prob be too difficult for non-programmers). Just wanted to clarify.

**Comment by johan-bjareholt** [comment] 2022-06-09 05:41
> no data is actually lost, it just takes some effort to consolidate again (which will prob be too difficult for non-programmers)

I guess, but that in essence means that it's essentially lost for almost all users.

**Comment by floriangeigl** [comment] 2022-06-10 11:17
quick thanks to you folks! rust version works perfectly - haven't had any timeout so far. queries return almost immediately. 🎉 thanks so much for helping me migrate :)

**Comment by Patitotective** [comment] 2022-07-06 00:31
After switching to the rust version it still timeouts on Ubuntu 22.04 with v0.11.0.
I also have the localhost:5666 problem.

Btw this is such a useful and cool project, thanks for your work. :heart:

**Comment by ErikBjare** [comment] 2022-07-13 12:41
I just implemented a 'request timeout' setting which lets users set their own max timeout, for large queries and such: https://github.com/ActivityWatch/aw-webui/commit/f75ac9d939b0841723dc00a23a3c575ecc25a5a9

It will be in the next release.

**Closed** 2022-07-13 12:54 UTC
Labels: type: bug
