### ISSUE TITLE
windows-watcher stopping without notice

### ISSUE THREAD

**Issue by theolundqvist** [ActivityWatch/activitywatch#990] opened 2023-11-14 14:33 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Ventura 13.5.1**: 
- **v0.12.2**: 

## Describe the bug

aw-watcher-window is sometimes not started. I can't find any errors in the logs. I am manually starting it in the activity bar menu a couple of times per day but and I am getting in to run from time to time. But most often I return to the following: 
<img width="344" alt="image" src="https://github.com/ActivityWatch/activitywatch/assets/31588188/9525f0f6-5e59-4501-9f9c-370eae369c9b">

## To Reproduce
No idea

## Expected behavior

Auto start aw-watcher-window and keep it running

## Additional context

ActivityWatcher is added to login items

**Comment by ErikBjare** [comment] 2023-11-14 15:01
Duplicate of #986

**Closed** 2023-11-14 15:02 UTC
Labels: type: bug, duplicate
