### ISSUE TITLE
Can't update start of day

### ISSUE THREAD

**Issue by Doezer** [ActivityWatch/activitywatch#716] opened 2022-02-22 08:33 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11, Using Edge for the webinterface
- **ActivityWatch version**: v0.11.0

## Describe the bug
I've got a clean install, just downloaded it.
When I try to update the start of day (typing in the field is enough to create the error), I have a `TypeError: Cannot read properties of undefined (reading 'value')` coming up.

```
TypeError: Cannot read properties of undefined (reading 'value')
    at change (:5600/js/chunk-44b75912.3b0ec1e3.js:1:107099)
    at ne (chunk-vendors.6671bb25.js:7:11664)
    at a.n (chunk-vendors.6671bb25.js:7:13484)
    at ne (chunk-vendors.6671bb25.js:7:11664)
    at a.Cn.t.$emit (chunk-vendors.6671bb25.js:7:26491)
    at a.onChange (chunk-vendors.6671bb25.js:38:135185)
    at ne (chunk-vendors.6671bb25.js:7:11664)
    at HTMLInputElement.n (chunk-vendors.6671bb25.js:7:13484)
    at HTMLInputElement.Ji.o._wrapper (chunk-vendors.6671bb25.js:7:51758)
```

I tried saving but it doesn't let me. 
I would change the categorization rules without any issues.

## To Reproduce
1. Go to the settings page
2. Try to update the start of day hour

## Expected behavior
No error

## Documentation
I've got no error in the server log, only heartbeats.
See a demo
![bug_activitywatch](https://user-images.githubusercontent.com/11655673/155093213-e1a5994b-4d1d-4249-89bc-c2d410a9fa14.gif)

**Comment by ErikBjare** [comment] 2022-03-03 13:30
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/681

Fixed in master and will be in the next release

**Closed by ErikBjare** 2022-03-03 13:30 UTC
Labels: type: bug, duplicate
