### ISSUE TITLE
Barchart not working on Linux

### ISSUE THREAD

**Issue by Kepler-69c** [ActivityWatch/activitywatch#631] opened 2021-07-04 16:25 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 20.04
- **ActivityWatch version** v0.11.0

## Describe the bug
After updating my activitywatch to the latest version, the timeline visualization (barchart) stopped working. I also got an error message:
```
TypeError: Cannot read property 'label' of undefined
    at TimelineBarChart.vue:99
    at _baseOrderBy.js:39
    at n (_arrayMap.js:16)
    at _baseOrderBy.js:38
    at _baseMap.js:17
    at _createBaseEach.js:24
    at o (_baseMap.js:16)
    at h (_baseOrderBy.js:37)
    at sortBy.js:45
    at n (_apply.js:15)
``` 

## To Reproduce
1. Start ActivityWatch
2. Click on the "Activity" Page
3. The chart remains empty and an error pops out

## Expected behavior
The bar chart visualization should be displayed on the "Activity" Page

## Documentation
![Screenshot2](https://user-images.githubusercontent.com/80059906/124392131-56b89380-dcf4-11eb-8413-498a603276b3.png)
![Screenshot1](https://user-images.githubusercontent.com/80059906/124392133-57512a00-dcf4-11eb-9ed1-27aadde9ecf3.png)

## Additional context
This error only occurs on Linux; I have also tried ActivityWatch on Windows 10 and MacOS BigSur, where it runs correctly.

**Comment by tgifford-webfirst** [comment] 2021-07-19 15:23
I also see this error. The datasets array contains a single undefined value.

**Comment by TransientError** [comment] 2021-08-11 13:17
I also experienced this bug. It seems to be caused by the category format changing. For me, the error message went away when I use the default categories.

I fixed this by exporting my categories as well as the default categories and trying to manually fix the format. The thing that ultimately fixed it for me was adding an "Uncategorized" category at the end like this:
```
    {
      "name": ["Uncategorized"],
      "rule": { "type": null },
      "data": { "color": "#CCC" },
      "name_pretty": "Uncategorized",
      "subname": "Uncategorized",
      "parent": null,
      "depth": 0,
      "id": <last id + 1>
    },
```
with the id number being the last entry + 1.

**Comment by ErikBjare** [comment] 2021-08-18 09:59
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/612.

Fixed in master, workarounds include:

 - Adding a top-level category named 'Uncategorized'
 - Resetting to default categories (which includes the 'Uncategorized' category)
 - Running from source (automatically adds the 'Uncategorized' category if missing)

**Closed by ErikBjare** 2021-08-18 09:59 UTC
Labels: type: bug, duplicate
