### ISSUE TITLE
TypeError: t is undefined

### ISSUE THREAD

**Issue by kev-dev1** [ActivityWatch/activitywatch#627] opened 2021-07-01 18:48 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11 21H2
- **ActivityWatch version**: v0.11.0
- 
## Describe the bug

When I watch my Activity´s from Today, became I a error messages who´s write "TypeError: t is undefined". And all my Activity´s are gray.

## Expected behavior
The Browser Konsole (Firefox) write "TypeError: t is undefined ..." (see Firefox-Console) and all the Activity have the color gray (see Picture)

## Documentation

aw-qt: [aw-qt_2021-07-01T18-39-14.log](https://github.com/ActivityWatch/activitywatch/files/6750158/aw-qt_2021-07-01T18-39-14.log)

aw-server: [aw-server_2021-07-01T18-39-18.log](https://github.com/ActivityWatch/activitywatch/files/6750160/aw-server_2021-07-01T18-39-18.log)

aw-watcher-window: [aw-watcher-window_2021-07-01T16-49-03.log](https://github.com/ActivityWatch/activitywatch/files/6750163/aw-watcher-window_2021-07-01T16-49-03.log)

Firefox-Console-log: [aw-localhost-page_firefox.txt](https://github.com/ActivityWatch/activitywatch/files/6750203/aw-localhost-page_firefox.txt)

Picture: 
![Screenshot 2021-07-01 at 20-47-24 ActivityWatch](https://user-images.githubusercontent.com/20777625/124175248-ace7c580-daad-11eb-89d7-aad729978545.png)

**Comment by ErikBjare** [comment] 2021-07-05 09:36
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/612, closing.

**Closed by ErikBjare** 2021-07-05 09:36 UTC
Labels: duplicate, type: bug
