### ISSUE TITLE
Taging activities into multiple categories (+allow plugin for tagging as anybody need)

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#192] opened 2018-05-08 12:02 UTC
It will be nice to tag every application, window title or regex on it into multiple categories for example.
Categories will be defined by user (no predefined categories is need for me - it is examples).

Category "time value" can be:
1. productive
2. unproductive
3. undefined/unknown

Category "activity" can be:
1. applications
2. games
3. communicators
4. browser
5. undefined/unknown

It will be nice to have subcategories so you can go deeper in reports what you do.
1. applications (graphics, programming, text, ..., undefined)
a. applications -> graphics
b. ...
2. programming (python, c++, ...)

It can be also some plugin doing such tagging externally (regex, Bayesian, ai ...) - so anyone can implement custom tagging.

I think that the most need is productive/unproductive filter and application types, other filters can be for work reporting but it is very specific and should be done by each person separately.

**Comment by ChameleonRed** [comment] 2018-05-08 12:06
Tags can be in such format like programming name spaces (top.lower.lower.lowest) in object programming - it is simple and commonly used.

activity.application.other, activity.application.programming, activity.application.graphics ...

time.productive, time.unproductive

**Comment by johan-bjareholt** [comment] 2018-05-08 13:42
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/95 but with some new ideas such as sub-categories. Closing this, let's keep the discussion in a single issue.

**Closed by johan-bjareholt** 2018-05-08 13:42 UTC

**Comment by ChameleonRed** [comment] 2018-05-08 23:14
Is #95 allows plugin for tagging?

**Comment by johan-bjareholt** [comment] 2018-05-09 06:36
@ChameleonRed Add a comment about it on the issue and we'll consider it when we start implementing. Since we value flexibility and modularity a lot that would seem like the right way to go about it.
