### ISSUE TITLE
Can't open dashboard on Mint KDE 18.2

### ISSUE THREAD

**Issue by ipsod** [ActivityWatch/activitywatch#150] opened 2017-12-05 14:07 UTC
After trying to open the dashboard, I get this error:

     kde-open5: /home/{user}/my_programs/activitywatch/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5)

Running Linux Mint KDE 18.2.

**Comment by ErikBjare** [comment] 2017-12-05 15:06
Sorry about that, it's been difficult for us to debug this issue. 

In the meantime you can just browse to http://localhost:5600/

Related issues:
 - https://github.com/ActivityWatch/aw-qt/issues/20
 - https://github.com/ActivityWatch/aw-qt/issues/29

**Comment by samm9876** [comment] 2018-03-02 22:10
Had the same problem on Mint, fixed it by copying "libstdc++.so.6.0.24" from the miniconda3 library into the activity watch folder and renaming it "libstdc++.so.6" to replace the original file.

I then got the error: "ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2"
Which I fixed by deleting the "libdrm.so.2" file.

Hope this helps.

**Comment by ErikBjare** [comment] 2018-03-18 12:17
Closing since the issue is resolved.

**Closed by ErikBjare** 2018-03-18 12:17 UTC
Labels: platform: linux, priority: low, type: bug
