### ISSUE TITLE
macOS Catalina complains repeatedly about an unverified developer

### ISSUE THREAD

**Issue by tivvit** [ActivityWatch/activitywatch#334] opened 2020-01-16 18:51 UTC
![Screenshot 2020-01-16 at 19 49 25](https://user-images.githubusercontent.com/3392931/72553637-6ee6e980-3899-11ea-82c8-ada58b7ffd8c.png)

How can I overcome this?

**Comment by rtpHarry** [comment] 2020-01-22 20:05
I've got stuck with this as well. I'm pretty new to macOS and looking for a good replacement from manictimer which I used on Windows.

I went through all of the executables in in the main folder and all the dyn libs; by going to the context menu, clicking open, and open on the dialog to bypass gatekeeper.

But after that it complained about `./PyQt5/QtCore.so` not being verified, which can't be done via the open method above.

I've tried to do it [via the terminal](http://osxdaily.com/2015/07/15/add-remove-gatekeeper-app-command-line-mac-os-x/) instead, and I did it by dragging the file onto terminal to ensure that the path was correct. 

It asked for my password which I supplied via touchid, but it didn't make any difference the next time I tried to run `aw-qt`.

I'm stuck!

**Comment by RobertoMaurizzi** [comment] 2020-01-25 06:35
I had/have it running on Catalina but the dialogs I got were a bit different:

0) start `./aw-qt`
1) It'll show a dialog saying something like "Sorry, no signature, I won't run this at all, move to bin" (there was no Open button, or it was greyed out)
2) After you get this go in "System Preferences / Security & Privacy / General": you'll see text close to the bottom of the window mentioning the offending file and a button to allow execution
2a) The first time only, before clicking the allow button, CLICK THE ICON TO BECOME ADMIN and type your password. If you don't the button will click, but it won't have any effect nor show any error (because Apple UX testing is sooo gooood :-p )
3) Click the "Allow" button in the Security & Privacy window. Keep its window open.
4) Your only option now is to cancel the existing error dialog then run again `./aw-qt`
5) This time around you'll get a dialog with a clickable "Open" button. Click it. After you click, you'll get another error dialog for a new binary with the only option to cancel or move to bin, just the same as in point 1). Press Cancel.
6) go back to 2) and repeat until you don't get any dialogs and it'll work. For me that was about 50 times...

If instead you're getting dialogs with an active "Open" button, I'd expect that you'll get around 50 of them (each asking for a different file) then aw-qt will start.

I do think that  install everything in a user-created virtual environment should avoid all these problems, at least until Apple makes impossible to compile your own Python and/or use pyenv. At that point I'll be time for me to start again using a different OS.

**Comment by tivvit** [comment] 2020-01-27 12:07
Maybe it would be better to run the server in docker?

Next, it would be nice to pack the monitoring script differently (to use system libraries). But I do not know if this is possible and if the maintainer is willing to do it. 

I am willing to help, but I have to examine the project and why is it distributed like this.

**Comment by johan-bjareholt** [comment] 2020-01-27 19:56
@tivvit 
Running the server in docker would eat up a lot of RAM and make the installation more complicated, if someone wants to do it themselves that's fine but having it as the recommended way to run ActivityWatch is out of the question. It's not even technically possible to run aw-qt or the watchers inside docker. Docker is not made for user applications and is a bad fit unless you only want to host aw-server. 

It is not possible to use system libraries because we use python and qt. The built-in python version in macOS is over a decade old and qt is not available.

There are improvements to the packaging of ActivityWatch for macOS to make it into an app bundle, go to the aw-qt to see the progress on that. Not sure if it solves any of these permission issues though.

**Comment by ErikBjare** [comment] 2020-01-28 06:00
We have a `.app` bundle almost ready here: https://github.com/ActivityWatch/activitywatch/pull/327

I also recently got an old MBP 2010 but I don't have Catalina running on it. However, the moment we have the PR merged I can give you a download to test out. If that's not enough, I will investigate registering with Apple to properly sign the `.app`.

**Comment by RobertoMaurizzi** [comment] 2020-01-31 06:27
Just today (while fighting with Logitech's device manager app that apparently forgets to tell you to give Input Monitoring permissions) I noticed that in Security & Privacy under Privacy there's a *Developer Tools* entry (on my Mac containing only *Terminal*) that apparently "Allows the apps below to run software locally that does not meet the system's policy".
That said, I can't wait for the offical .app, thanks @xylix :-D

**Comment by xylix** [comment] 2020-02-15 12:38
@tivvit @rtpHarry @RobertoMaurizzi 

Update: I have now updated my macOS to Catalina and (at least) the newest master works as expected after code signing with a self-made certificate. If you want to sign yourself, [these instructions] (https://stackoverflow.com/a/27474942/6734941) should be enough, expect change the codesign arguments to:

`codesign --deep -s "your new cert" /Applications/ActivityWatch.app`

If anyone is interested you can try my self signed version from [here](https://drive.google.com/open?id=1zReaVoYaJ45dvntMpfQouxicEAKFKQkg). It is not an official build, but I will help you debug macOS specific issues with this build or any self-built version, so we can get ActivityWatch on macOS working as smooth as possible :).

I'm working on getting the code signing to work in our CI, but it will take some time.

**Comment by rtpHarry** [comment] 2020-02-18 20:18
I tried the self-signed version on your Google drive but that didn't work:

![image](https://user-images.githubusercontent.com/1038062/74774491-c65ae980-528b-11ea-8aad-84a129594051.png)

Will investigate the other option.

**Comment by xylix** [comment] 2020-03-01 09:45
Sorry about the problems, but progress is being made. The problem with the .zip was my zipping tools messing up some metadata which made the signature invalid.

@rtpHarry A new signed dmg is here https://drive.google.com/open?id=1KPNPIND8jGFVq21fAoV7KICLadP3Nwg- . 

Try it out if you can. CI support is still in progress.

**Comment by rtpHarry** [comment] 2020-03-01 19:50
Aww yissss! :) It has installed and opened. It seems to be collecting data. I've given it the permissions it wants. I'll report back after a few days usage.

**Comment by tivvit** [comment] 2020-03-09 11:48
works for me

**Comment by xylix** [comment] 2020-03-11 13:41
We'll be releasing an official 0.9 very soon with a signed dmg.

**Comment by xylix** [comment] 2020-03-15 17:28
Have any of you running the .app had issues with window titles not being recorder?

**Comment by rtpHarry** [comment] 2020-03-15 22:24
Not had that problem, no

**Comment by rtpHarry** [comment] 2020-03-19 23:52
is it possible to get this build to auto start on load? I can't find a setting or anything in the properties of the .app

**Comment by rtpHarry** [comment] 2020-03-19 23:54
oops brain is not working, didn't google it first (https://www.idownloadblog.com/2015/03/24/apps-launch-system-startup-mac/)

**Comment by vitorgalvao** [comment] 2020-03-20 00:47
I’m not a user of this software, but this [is being submitted to Homebrew Cask](https://github.com/Homebrew/homebrew-cask/pull/78920/files) and I was interested in the self-signing approach.

Self-signed certificates are not meant to be accepted by Gatekeeper, and sure enough this still doesn’t seem to fix the issue in the top post.

I’ve tried both the DMG on [the `0.9.0` release](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.9.0) and the one [on Google Drive](https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-593076612) *on a clean VM*. They still report this as being from an unidentified developer and behave like any unsigned download.

**Comment by xylix** [comment] 2020-03-20 14:07
@vitorgalvao Yes the .dmg needs the user to manually "open anyway" through the security menu. After that there should be no more popups on future openings of the application, which is the best result we could get through self signing.

**Comment by vitorgalvao** [comment] 2020-03-20 14:09
> which is the best result we could get through self signing.

And is exactly the same result you get from an app that isn’t signed. My point is exactly that self-signing does nothing in this context.

**Comment by xylix** [comment] 2020-03-20 14:10
Oh. I'll test an unsigned .dmg then.

**Comment by xylix** [comment] 2020-03-21 09:48
Did a new build and confirmed self-signing the .dmg doesn't make a difference.

@ErikBjare usage of the .app is possible on Catalina without signing, but the warnings will always happen if we don't get the official apple developer license.

This issue's original problem which was that all the script files contained in the /activitywatch folder needed to be given permission one at a time is fixed with the .dmg / .app packaging though.

**Comment by rtpHarry** [comment] 2020-03-29 14:44
@xylix yes I am getting the no titles being recorded issue now. Still running the same custom build that you gave me. 

One thing I changed was to make the app auto load on startup. Could it be that it gets some different permissions when loaded this way? 

I have also installed the latest macos update that came out, but I suppose that's unlikely the culprit if you have been experiencing it before then.

**Comment by rtpHarry** [comment] 2020-03-29 14:52
Hmm I just looked through the logs and it seems like the last title it recorded was me starting the latest catalina system update:

![image](https://user-images.githubusercontent.com/1038062/77852204-3470c580-71d5-11ea-9957-e39f9a0a8370.png)

**Comment by xylix** [comment] 2020-03-30 16:05
@rtpHarry Good info. As a possible fix, could you try removing `ActivityWatch` from your allowed accessibility permissions and re-adding it?

I'm also working on a clearer "missing permissions reporting" over at aw-watcher-window, but it'll take some time to be ready for use.

**Comment by rtpHarry** [comment] 2020-03-30 20:41
Good call! That restores the titles, yes:

![image](https://user-images.githubusercontent.com/1038062/77959784-1ab3a900-72cf-11ea-9825-e10122d47cca.png)

**Comment by rtpHarry** [comment] 2020-03-31 10:22
fyi the same issue happened when I went to the site and downloaded the 0.9.2 dmg and installed it - no titles until I removed and re-added accessibility permissions

**Comment by jankatins** [comment] 2020-04-23 19:42
I've installed activitywatch by downloading the the activitywatch-v0.9.2-macos-x86_64.dmg file, dragging the icon to application and then went to /Application, clicked right->open, answered the security question and got an icon in my tray/menu bar. Unfortunately, now my system has about 60% of an CPU running trustd, syspolicyd and my virus scanner.

I can trigger this by quitting activitywatch via the menu icon (all processes stop using CPU) and restarting it (all start up again). Unfortunately, this is already enough to start the fan spinning, so it's quite annoying :-(

**Comment by rtpHarry** [comment] 2020-04-24 07:22
@jankatins I had some heavy usage spike with it and thought it was going to be a big drain, but I think that's just the initial scan from your virus checker. Once it has read all the files and scanned them it should settle down. The power usage on my laptop now is negligible, and I've been using this for a month or two. Perhaps give it a bit of time to see if it settles down?

**Comment by jankatins** [comment] 2020-04-24 14:08
Sorry, should have realized this: https://github.com/ActivityWatch/aw-watcher-window/issues/45

I started this comment when I was still thinking this was related to the signing problem because lot's of syspolicy google hits pointed to certificate checks.

**Comment by grigorye** [comment] 2020-05-16 23:27
I'm not sure whether this is relevant, but that I see "System Events.app" eating some noticeable amount of CPU (10%) with Activity Watch 0.9.2 and aw-watcher-window enabled.

**Comment by xylix** [comment] 2020-05-25 08:00
@grigorye  I think the CPU usage is related to https://github.com/ActivityWatch/aw-watcher-window/issues/45 . Not confirmed right now though.

**Comment by seantms** [comment] 2020-11-21 05:03
I tried installing this recently, but macOS Catalina did not show the "Open Anyway" option. 

Had to do a "sudo spctl --master-disable" which I believe disables Gatekeeper, so you should do a "sudo spctl --master-enable" once done with the installation and giving it the permissions it needs. 

You can read up more here: https://en.wikipedia.org/wiki/Gatekeeper_(macOS)

**Comment by ErikBjare** [comment] 2020-11-24 13:42
>but macOS Catalina did not show the "Open Anyway" option.

@seantms I tried this today, and when first trying to open it I didn't get the option on the dialog, but when I tried again there was an "Open Anyway" button :man_shrugging:

I'm running the latest v0.10.0 `.app` on a clean Catalina VM, and apart from "unverified developer" warnings things are working fine (as well as the dialog we open to tell the user to give us Accessibility permissions getting drowned under other open windows). Didn't need to do `sudo spctl --master-disable`.

**Comment by TheTimeWalker** [comment] 2021-05-03 07:42
I just want to note for Big Sur (and possibly Catalina), you don't have to fully disable Gatekeeper to get the Open Anyway option. When you move the app into the Applications folder, you can just open the Context menu (hold CTRL or right click) and then select Open. This actually is different from double-clicking and opens up a different pop up that adds in the option to "Open Anyway".

**Comment by drthegirlfriend** [comment] 2021-08-09 11:01
To comment on this thread, on a macbook pro m1 big sur 11.4, I had to allow _every single script_ to get the program to run at all...this took a full hour of starting the /aw-qt and reclosing and accepting 'run anyways' to each single complaint until it worked without errors, the .app refused to work at all. So to those who want to use it, it does certainly work eventually.

**Comment by may** [comment] 2022-02-26 18:02
Update on this thread for anyone who got here from the Downloads page.

To get Activty Watch working on MacOS Monterey 12.2.1:
1. Download v 11 (the latest at the time of this writing.)
2. Open the .dmg file and drag the app into Applications as usual. 
3. Launch the app. Note that it doesn't launch/the permissions dialgoue you get doesn't give you an option to allow.
4. Open System Preferences.
5. Go to System Preferences -> Security and Privacy
6. Ensure you are on the General tab, and you see something towards the bottom that says 'MacOS prevented Activity Watch from running....' just click Open or Allow, then you get another scary popup, click Open on there. 
7. Activity Watch should now be running.
8. Notice that your timeline is full of 'unknown application'
9. Go back to System Preferences
10. Navigate again to System Preferences -> Security & Privacy
11. Go to the Privacy tab
12. Select 'Accessibility' on the left. Activity Watch may or may not be listed under 'Allow the apps below to control your computer'. If it is, click the lock to unlock, authenticate, and click the checkmark next to Activity Watch.
13. If Activity Watch isn't listed, click the plus icon and find it in the lookup (within the Applications folder). 
14. Then click the checkmark next to Activity Watch.

When you're done, it should look like this (note Activity Watch at the top of the greyed out list): 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/82888/155854095-0df98ca0-ede6-453f-8f31-73438e73d6fe.png">

Finally, for the devs who may read this:
1. Thank you. I think this will be better than RescueTime. I just need to look and see if there's a goals function.
2. Please note that when I tried v0.10 it PROMOTED me for Accessibility permissions. Restoring that in v0.11 or v0.12 will probably help new users. That said, I know that's Apple changing things on you, but I wanted to mention it.

**Comment by ErikBjare** [comment] 2022-02-27 09:55
@may That is very helpful, thanks!

**Comment by may** [comment] 2022-03-01 15:02
An alternative approach I am trying is explicitly giving Accessibility permissions to all parts of ActivityWatch.
1. Open System Preferences -> Security & Privacy -> Accessibility.
2. Open Finder -> Applications -> right-click ActivityWatch -> Show Package Contents
3. In Finder, within the ActivityWatch folder you just opened: navigate to Contents -> MacOS.
4. Drag each of the following into the Security & Privacy window, giving them each accessibility permissions:

- aw-qt
- aw-server
- aw-watcher-afk
- aw-watcher-window

Perhaps we only need to give aw-watcher-window the permissions, but it doesn't hurt to be through. 

I will test this and update this comment if it works consistently. 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/82888/156193192-47fa7c9d-c698-42a1-bf63-e949585648cb.png">

**Comment by piktonus97m** [comment] 2022-03-09 14:41
Thanks @may I was able to replicate this in Monterey 12.2.1 Intel using [these instructions](https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-1052392579). Everything looks good so far. 

Just want to mention that the Terminal won't show up under Automation, if you have not used it before for background process. As May mentioned, this step is only to double check, but if it does not appear, no worries, you can try to run the file.command, and it will show up. :)

**Comment by ErikBjare** [comment] 2022-03-11 16:23
Can someone try this with the new v0.12.0b1 beta? The `.app` is now properly codesigned: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.0b1

It might not open when double-clicked (unrelated bug), but should open if run from terminal with `open ./ActivityWatch.app`

**Comment by may** [comment] 2022-03-12 21:23
@ErikBjare Code signing improved, still permissions issues, but we can work around permissions issues.

1. Quit ActivityWatch.
2. Download and open 0.12.0b1: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.0b1
3. Drag to Applications folder.
4. System Preferences -> Privacy -> Accessibility -> Remove any existing Activity Watch entries. 
5. Click the plus and add the new Activity Watch from Applications.
6. You may need to exit System Preferences between step 4 and 5.
7. Launch Activity Watch from Applications folder. Notice that it is codesigned now and doesn't warn about scary unknown devs.
8. Click the Activity Watch icon, click Open Dashboard. 
9. Notice that no data is being displayed from the watcher. 
10. Notice that Activity Watch, when launched, does not prompt for any permissions. 

Error message for Activity Watch window watcher is as follows:
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.
2022-03-12 15:18:45 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:75)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 72, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 55, in get_current_window
  File "aw_watcher_window/lib.py", line 27, in get_current_window_macos
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.


11. Quit Activity Watch.
12. Use Terminal method described in

**Comment by x-zheng16** [comment] 2022-03-28 11:02
I found a better choice. For macOS Monterey 12.3, after downloading aw v11 and installing it, I create a new symbolic link by 
`ln -s /Applications/ActivityWatch.app/Contents/MacOS/aw-qt ~/Applications/aw-qt`, then add `~/Applications/aw-qt` to the login items. I noticed that `~/Applications/aw-qt` can work well without breaking the icon in the menu, that is, aw can be closed correctly by clicking the icon in the menu and selecting "Quit ActivityWatch".

I also chose to install aw from source but it broke after several days and I have to uninstall it.

**Comment by stpn** [comment] 2022-05-10 05:10
@may Thanks for your suggestion - your method allows to launch ActivityWatch successfully, however it seems that it produces another issue - I cannot quit Chrome, as it automatically restarts. Any chance you'd have some suggestion on how to address that? 
Thank you

**Comment by may** [comment] 2022-05-13 17:48
@stpn No idea why that'd be the case, but I'm glad to hear about it since I've been having problems with chrome not quitting too. All the script is doing is starting ActivityWatch from the command line, with proper permissions.

**Comment by vishalkrv** [comment] 2022-06-04 06:14
@may Thank you for putting up the installation steps, I was able to install v0.12.0b2 on M1 Monterey 12.2.4 and everything seems to be working including firefox integration, vscode integration and window title.

**Comment by JonThom** [comment] 2022-06-20 11:46
Hi guys, Gatekeeper blocks ActivityWatch on MacOS 12.2.1 (“ActivityWatch” cannot be opened because the developer cannot be verified.)
Haven't gone through every comment above, but I suppose this is due to code signing, and most likely Qt.
I myself had to struggle to get a Qt app bundle (using QtWebEngine via PySide6 in Python) codesigned and notarized, but managed in the end

**Comment by dingwen07** [comment] 2022-07-21 08:29
@may 
Find another workaround of directly adding the permission: https://github.com/ActivityWatch/activitywatch/discussions/768

**Comment by ErikBjare** [comment] 2022-09-26 14:56
Hi all,

I bought a MacBook Air M2 last week just so I can finally resolve all the macOS issues, and today I bring good news: 

I've managed to merge https://github.com/ActivityWatch/aw-watcher-window/pull/68 which changes how window titles are tracked, and seems to be a lot more robust (solves a bunch of issues with the current method). I'm almost done with the finishing touches, and hopefully everything will "Just Work™️" once the release is out.

I know you all have strugged getting ActivityWatch to run on macOS, and hopefully this is the last thing needed to get it working without issue.

Thank you all for your patience and support. Stay tuned for a new release.

**Comment by ErikBjare** [comment] 2022-09-26 19:58
Please try this new release and see if things have improved: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.1

**Comment by ErikBjare** [comment] 2022-09-28 07:36
From all I've heard from users, this issue has been resolved.

Thank you all for your comments!

**Closed by ErikBjare** 2022-09-28 07:36 UTC
Labels: platform: macos, improves: ux, improves: retention, improves: onboarding
