### ISSUE TITLE
[Beta][Windows]: tray menu is shown on other display in multi-display configuration

### ISSUE THREAD

**Issue by PetbkA** [ActivityWatch/activitywatch#964] opened 2023-10-08 14:57 UTC
- [x] I am on the [latest **beta v0.12.3b9**](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b9) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 LTSC 2021 (version 21H2) x64 EN
- **ActivityWatch version**: 0.12.3b**9**

## Describe the bug
Tray menu is shown [on other display](https://github.com/ActivityWatch/activitywatch/assets/22843816/69d590df-c1b6-4bae-b327-23e3f8e0edb1) in multi-display configuration. Don't remember exactly when the problem appeared in beta, but everything was OK in [v0.12.2](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2).

## To Reproduce
1. Press right mouse button to open tray menu - NOK, menu is shown [on other display](https://github.com/ActivityWatch/activitywatch/assets/22843816/69d590df-c1b6-4bae-b327-23e3f8e0edb1).

## Expected behavior
Tray menu will be shown on the display where tray icon was pressed

**Comment by ErikBjare** [comment] 2023-10-16 15:01
I have no idea what is causing this, but it's definitely related to Qt and not something we can do much about. The only solution I can imagine is to wait and see if Qt resolves this in a future update.

Since I have no lead other than waiting for Qt to resolve this upstream, and the issue is minor, I will close the issue.

But thanks for reporting!

**Closed by ErikBjare** 2023-10-16 15:01 UTC
Labels: type: bug
