### ISSUE TITLE
ActivityWatch is not showing reports in the web dashboard (with proxy)

### ISSUE THREAD

**Issue by heliocarbex** [ActivityWatch/activitywatch#360] opened 2020-03-02 13:52 UTC
## Describe the bug
ActivityWatch is not showing reports in the web dashboard.

## To Reproduce
Just start the aw-qt.exe

## Expected behavior
Seeing the following message in the dashboard: "No activity reports available. Make sure you have both an AFK and window watcher running".

## Documentation
Error print screen
![image](https://user-images.githubusercontent.com/249042/75682277-e919d480-5c73-11ea-9ef1-844505431620.png)

All the process are running, as can been seen in the Task Manager:
![image](https://user-images.githubusercontent.com/249042/75682196-c4256180-5c73-11ea-9b05-edbf720bbc55.png)

Log files
[aw-watcher-afk_2020-03-02T10-40-59.log](https://github.com/ActivityWatch/activitywatch/files/4275704/aw-watcher-afk_2020-03-02T10-40-59.log)
[aw-watcher-window_2020-03-02T10-40-59.log](https://github.com/ActivityWatch/activitywatch/files/4275709/aw-watcher-window_2020-03-02T10-40-59.log)
[aw-server_2020-03-02T10-40-59.log](https://github.com/ActivityWatch/activitywatch/files/4275711/aw-server_2020-03-02T10-40-59.log)
[aw-qt_2020-03-02T10-40-57.log](https://github.com/ActivityWatch/activitywatch/files/4275712/aw-qt_2020-03-02T10-40-57.log)

## Environment
 - ActivityWatch version: v0.8.4
 - OS: Windows 10

**Comment by ErikBjare** [comment] 2020-03-10 12:31
Which buckets do you have in the "Raw Data" view? Is the data there up to date?

**Comment by johan-bjareholt** [comment] 2020-03-10 12:46
The logs says that it cannot connect to the server, it's likely some local setup such as a proxy messing up the connection between the watchers and aw-server.

**Comment by heliocarbex** [comment] 2020-03-10 12:54
I am inside a corporate network. @johan-bjareholt , you are right. I have the variables HTTP_PROXY and HTTPS_PROXY in a particular setting, when I unset it, the activitywatch is working.

**Comment by heliocarbex** [comment] 2020-03-10 12:55
Is there a way to make activitywatch ignore proxy settings?

**Comment by johan-bjareholt** [comment] 2020-03-11 09:31
> Is there a way to make activitywatch ignore proxy settings?

Easiest way is to simply start the activitywatch watchers without HTTP_PROXY and HTTPS_PROXY set. That's what I do at work at least.

**Comment by ErikBjare** [comment] 2020-03-11 14:41
Closing since the cause of the issue is resolved.

**Closed by ErikBjare** 2020-03-11 14:41 UTC
Labels: platform: windows, type: bug
