### ISSUE TITLE
Uncaught TypeError on mouseout event

### ISSUE THREAD

**Issue by Aprizotec** [ActivityWatch/activitywatch#843] opened 2023-01-20 18:33 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**:  Windows 11 version 22621.1105
- **ActivityWatch version**: v0.12.1

## Describe the bug
When the mouse leaves a "day" rect in this svg,
![image](https://user-images.githubusercontent.com/65119813/212984113-52873e85-ce57-44cf-a2e4-83f3f714f188.png)

this error is thrown in the devtools console:
```
periodusage.js:111 Uncaught TypeError: Cannot read properties of undefined (reading 'undefined')
    at SVGRectElement.<anonymous> (periodusage.js:111:19)
    at SVGRectElement.<anonymous> (on.js:3:14)
```

## To Reproduce

1. Open the dashboard via the tray icon
2. Click on `Activity` in the top left corner
3. Move the mouse over a "day" rect
4. Move the mouse outside of the "day" rect
5. Open devtools console
6. See error

## Expected behavior
When the mouse leaves a "day" rect, no error should be thrown and the color should return to normal.

**Comment by BelKed** [comment] 2023-01-20 18:48
Duplicate of https://github.com/ActivityWatch/aw-webui/issues/393

**Closed** 2023-01-24 13:27 UTC
Labels: type: bug
