### ISSUE TITLE
Crash on Windows 7 64bit

### ISSUE THREAD

**Issue by hao-lee** [ActivityWatch/activitywatch#374] opened 2020-03-15 07:04 UTC
## Describe the bug

`aw-qt.exe` will crash on my system instantly. Running this program in cmd doesn't give any detailed logs.

![image](https://user-images.githubusercontent.com/8112645/76697066-49c1fc00-66cd-11ea-96fd-7a2dedae9c74.png)

## Documentation

I can't find any logs in `C:\Users\<USER>\AppData\Local\ActivityWatch\Logs`.

## Environment
 - activitywatch-v0.8.4-windows-x86_64-setup.exe
 - OS: Windows 7

**Comment by ErikBjare** [comment] 2020-03-15 08:03
This is a known issue, duplicate of #91. Won't be fixed because Windows 7 is EOL and there's unlikely a contributor is willing to pick it up. 

Closing.

**Closed by ErikBjare** 2020-03-15 08:03 UTC
Labels: duplicate, platform: windows
