### ISSUE TITLE
Activity watch not detecting watch time from media players like MPV and VLC

### ISSUE THREAD

**Issue by Pineapplenuts** [ActivityWatch/activitywatch#988] opened 2023-11-12 02:08 UTC
- [ x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ x] I have searched the issues of this repo and believe that this is not a duplicate.

Manjaro Linux Update: 2023-11-11 15:50 
Version:  v0.12.3b12

## Describe the bug

Activity watch detects this time as away from keyboard time instead of time used watching media

## To Reproduce

  Open any video file in MPV and  VLC and just watch the content.

## Expected behavior

The time spent watching the content is allocated under the program name, eg under MPV and allocated under the media > video category similar to how content watched in youtube is allocated  

## Additional context
![Screenshot from 2023-11-11 22-14-37](https://github.com/ActivityWatch/activitywatch/assets/91295884/90b52a60-4f51-484d-adae-c33a05a2ba0e)
VLC is supposed to be approx 1 hour 30 min because of the movie i was watching was over 2 hours in length at 10% speed increase minus 33 minutes watched in mpv at 21% speed increase. MPV is also not including for watch because it would be approx 28 mins of watch time.

**Comment by BelKed** [comment] 2023-11-12 02:55
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/261

**Comment by ErikBjare** [comment] 2023-11-12 13:46
There is no magic solution here.

You can add your video player to the "always count as active" pattern in settings, but then you risk false negatives if you leave your player open while you're inactive.

Closing in favor of #261 where this has already been discussed extensively.

**Closed** 2023-11-12 13:49 UTC
Labels: type: bug, duplicate
