### ISSUE TITLE
VirusTotal 4 engines detect Malware 

### ISSUE THREAD

**Issue by sk3pp3r** [ActivityWatch/activitywatch#452] opened 2020-07-02 06:28 UTC
VirusTotal - 4 engines detect Malware / risk 

beb047cb7583df66301493c613afe0d7bf6c62b5445eb38797b6fcf38d239afe

[](https://www.virustotal.com/gui/file/beb047cb7583df66301493c613afe0d7bf6c62b5445eb38797b6fcf38d239afe/detection
)

**Comment by johan-bjareholt** [comment] 2020-07-02 06:32
This is not a bug on our side, it's a bug on the virus scanner.
The point of a virus scanner is to find potential threats, it can never be sure if it is a real threat or not.

If you'd like to help we'd appreciate if you reported the false positive to VirusTotal, many virus applications take in submissions of false positives.

**Comment by johan-bjareholt** [comment] 2020-07-02 06:33
It's essentially a duplicate of this issue

https://github.com/ActivityWatch/activitywatch/issues/140

**Closed by johan-bjareholt** 2020-07-02 06:33 UTC
Labels: type: bug
