### ISSUE TITLE
Firefox detect virus on Windows. .exe

### ISSUE THREAD

**Issue by bitpaint** [ActivityWatch/activitywatch#668] opened 2021-09-18 12:58 UTC
![image](https://user-images.githubusercontent.com/67663265/133889545-ba431f02-157e-4354-b87f-375f8e99c3cc.png)
![image](https://user-images.githubusercontent.com/67663265/133889553-383ee88a-e24c-412d-9bb7-7aa21724c78d.png)

Certainly a false flag bug i report it anyway.
Virustotal: https://www.virustotal.com/gui/file/00a6f5cf0bb7d75924387f4cc0c9cf5be563275d7f23df2af04a86d162aca327/relations

**Comment by ErikBjare** [comment] 2021-09-20 09:12
Duplicate of #181

**Closed by ErikBjare** 2021-09-20 09:12 UTC
Labels: duplicate
