### ISSUE TITLE
If there is a space in the path name "make build" fails

### ISSUE THREAD

**Issue by theguybieber** [ActivityWatch/activitywatch#61] opened 2017-06-02 14:03 UTC
This is a minor one. If there is a space in the path name that you are building from the make build fails. For me this failed on a npm command. This probably can be fixed by adding quotes around path names.

**Comment by ErikBjare** [comment] 2017-06-02 19:16
I can't reproduce this on my machine, could you get a stacktrace?

**Comment by ErikBjare** [comment] 2017-06-07 01:18
Needs reproduction, closing since building from an uncommon path isn't a valuable bug to fix given the existing workaround of simply move the build folder. If anyone is able to reproduce and provides logs I'll reopen.

The reporter was using macOS if I'm not mistaken, perhaps that matters.

**Closed** 2017-06-07 01:19 UTC
Labels: needs: reproduction, size: small, unresolved
