### ISSUE TITLE
Windows client random crashes with no error - Event ID 1000

### ISSUE THREAD

**Issue by ovidiuc** [ActivityWatch/activitywatch#561] opened 2021-02-10 12:13 UTC
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 19042.804
- **ActivityWatch version**: v0.10.0

## Describe the bug
The system tray icon crashes randomly when I right click it, to open the menu. No error is displayed. The menu does not open and after a few seconds the icon disappears. It works fine if I run it again.

There are 2 events related to this in Event Viewer:

```
Faulting application name: aw-qt.exe, version: 0.0.0.0, time stamp: 0x5d24a2c1
Faulting module name: Qt5Gui.dll, version: 5.10.1.0, time stamp: 0x5a7c816f
Exception code: 0xc0000005
Fault offset: 0x0000000000072920
Faulting process id: 0x3624
Faulting application start time: 0x01d6ff91494f9a7d
Faulting application path: C:\Users\myusername\AppData\Local\Programs\ActivityWatch\aw-qt.exe
Faulting module path: C:\Users\myusername\AppData\Local\Programs\ActivityWatch\Qt5Gui.dll
Report Id: 0169413a-b180-4c0c-bcff-df4f7795e58e
Faulting package full name: 
Faulting package-relative application ID: 
```

and 

```
Faulting application name: aw-qt.exe, version: 0.0.0.0, time stamp: 0x5d24a2c1
Faulting module name: Qt5Gui.dll, version: 5.10.1.0, time stamp: 0x5a7c816f
Exception code: 0xc000041d
Fault offset: 0x0000000000072920
Faulting process id: 0x3624
Faulting application start time: 0x01d6ff91494f9a7d
Faulting application path: C:\Users\myusername\AppData\Local\Programs\ActivityWatch\aw-qt.exe
Faulting module path: C:\Users\myusername\AppData\Local\Programs\ActivityWatch\Qt5Gui.dll
Report Id: 200eb4ef-1377-464a-8509-21f8007607fc
Faulting package full name: 
Faulting package-relative application ID: 
```

Another thing worth mentioning is that events are logged before I initiate the click action. Couldn't find a gap in event logging.

## To Reproduce
I am not able to replicate, as it happens randomly. My guess is crashes after some idle time (so maybe related to AFK). But can't be sure.

But when it does happen, I just right click the icon, trying to open the menu.

## Expected behavior
The system tray menu should open.

## Documentation
There are no errors in the logs at the time of the crash or before it. The only thing that stands out is this exception from `aw-watcher-window`:

```
2021-02-10 13:56:25 [ERROR]: Exception thrown while trying to get active window: (-2147217385, 'OLE error 0x80041017', None, None)  (aw_watcher_window.main:71)
```
which happens multiple times, but not directly related to the crash.

**Comment by johan-bjareholt** [comment] 2021-02-13 16:46
Thanks for reporting, have not heard of a similar issue before.

We can't unfortunately do much if we can't reproduce as we don't have any good guesses at what might be going wrong.

**Comment by ErikBjare** [comment] 2021-08-18 10:06
Not much to go on here. If the issue persists in v0.11 and later, let us know.

Closing.

**Closed by ErikBjare** 2021-08-18 10:06 UTC
Labels: type: bug, !unresolved
