### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by postiveguy14** [ActivityWatch/activitywatch#922] opened 2023-07-27 06:08 UTC
![image](https://github.com/ActivityWatch/activitywatch/assets/82219320/4a083986-eb00-4387-9b72-fdca80441923)

I am able to run the server and i am not able to access `http://localhost:5600`. Please help me how to run it

- [ ] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by BelKed** [comment] 2023-07-27 08:07
Thanks for reporting, this issue is a duplicate of https://github.com/ActivityWatch/aw-server/issues/143.
In the meantime, please downgrade to [`v0.12.3b3`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b3), which seems to work fine.

**Closed** 2023-08-02 08:14 UTC
