### ISSUE TITLE
Hovering over the bars in the histogram with each day turns the bar blue permanently

### ISSUE THREAD

**Issue by ArthurusDent** [ActivityWatch/activitywatch#846] opened 2023-02-13 15:15 UTC
I'm using Firefox 109.0.1 on Windows 10 and whenever I hover over a bar of the histogram with the different days, that bar turns blue permanently. The site needs to be reloaded for it to show up normally again.

![grafik](https://user-images.githubusercontent.com/6848629/218495284-2a80452b-f492-487a-93d5-734eb984a651.png)

The "bug" isn't new. It was introduced a longer time ago, maybe half a year. Since it didn't get fixed, I'm reporting it now. Or maybe it didn't get reported because it is a rare bug? Maybe Firefox is the culprit here?

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by ArthurusDent** [comment] 2023-02-13 15:29
Sorry, I should have checked Chrome before reporting. The problem occurs in Chrome 110.0.5481.78. This is probably a problem in AW.

**Comment by BelKed** [comment] 2023-02-13 17:03
Duplicate of https://github.com/ActivityWatch/aw-webui/issues/393

**Closed** 2023-02-13 18:04 UTC
