### ISSUE TITLE
Can't start v0.9.2

### ISSUE THREAD

**Issue by sojusnik** [ActivityWatch/activitywatch#389] opened 2020-03-23 17:07 UTC
When launching, the following error message of the window `aw-qt` appears:

`Module aw-server quit unexpectedly`

The details show:
```
2020-03-23 09:35:22 [INFO ]: Using storage method: peewee  (aw_server.main:26)
2020-03-23 09:35:22 [INFO ]: Starting up...  (aw_server.main:31)
2020-03-23 09:35:22 [INFO ]: Using database file: /home/sojusnik/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:90)
2020-03-23 09:35:22 [INFO ]:  * Running on http://localhost:5600/ (Press CTRL+C to quit)  (werkzeug:122)
2020-03-23 09:35:33 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_mir)  (aw_server.api:228)
2020-03-23 09:35:44 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-web-firefox)  (aw_server.api:228)
2020-03-23 15:34:26 [INFO ]: 404 (127.0.0.1): GET /img/icons/apple-touch-icon-152x152.png HTTP/1.1  (flask:25)
2020-03-23 15:34:28 [WARNING]: Gap was of negative duration but could be safely merged (-506.583s). This message will only show once per batch.  (aw_transform.flood:46)
2020-03-23 15:35:04 [WARNING]: Gap was of negative duration but could be safely merged (-506.583s). This message will only show once per batch.  (aw_transform.flood:46)
2020-03-23 15:35:09 [WARNING]: Gap was of negative duration but could be safely merged (-506.583s). This message will only show once per batch.  (aw_transform.flood:46)
2020-03-23 15:35:13 [WARNING]: Gap was of negative duration but could be safely merged (-506.583s). This message will only show once per batch.  (aw_transform.flood:46)
2020-03-23 15:35:15 [WARNING]: Gap was of negative duration but could be safely merged (-506.583s). This message will only show once per batch.  (aw_transform.flood:46)
```

aw-qt.log:
```
2020-03-23 17:49:34 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-03-23 17:49:34 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:49)
2020-03-23 17:49:34 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:49)
2020-03-23 17:49:35 [INFO ]: Creating trayicon...  (aw_qt.trayicon:140)
2020-03-23 17:50:01 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:87)
2020-03-23 17:50:01 [INFO ]: Starting module aw-server-rust  (aw_qt.manager:49)
2020-03-23 17:50:01 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-03-23 17:50:01 [INFO ]: Stopped module aw-watcher-afk  (aw_qt.manager:97)
2020-03-23 17:50:01 [INFO ]: Stopped module aw-watcher-window  (aw_qt.manager:97)
2020-03-23 17:50:01 [INFO ]: Stopped module aw-server  (aw_qt.manager:97)
2020-03-23 17:50:01 [INFO ]: Stopped module aw-server-rust  (aw_qt.manager:97)
2020-03-23 17:50:01 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-03-23 17:50:03 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:87)
2020-03-23 17:50:09 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-03-23 17:50:11 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:87)
2020-03-23 17:50:28 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-03-23 17:50:29 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:87)

```

aw-watcher-window.log
```
2020-03-23 17:49:35 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:40)
2020-03-23 17:49:36 [WARNING]: Not connected to server, 0 requests in queue  (aw_client.client:380)
2020-03-23 17:49:46 [WARNING]: Not connected to server, 0 requests in queue  (aw_client.client:380)
2020-03-23 17:49:56 [WARNING]: Not connected to server, 2 requests in queue  (aw_client.client:380)
```

At least the tray icon is back :)

Happens with Ubuntu 19.10.

**Comment by ErikBjare** [comment] 2020-03-23 17:15
Yeah sorry, aw-server crashed on start (presumably on all platforms). I deleted v0.9.2 and just republished. It's building right now and builds will be available momentarily :)

**Comment by ErikBjare** [comment] 2020-03-23 17:36
v0.9.2 was just released and fixed this. I'll mark this as a duplicate of #378 and close it. Thanks for quick reporting :)

**Closed by ErikBjare** 2020-03-23 17:36 UTC
Labels: duplicate, pyinstaller

**Comment by omidraha** [comment] 2020-10-23 01:52
I have the same issue on `v0.9.2`

I download [latest](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.9.2) version and start it form cmdline an also double click on `aw-qt`:

Starting log:

```
$  ./aw-qt 
2020-10-23 05:13:14 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-10-23 05:13:14 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:49)
2020-10-23 05:13:14 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:49)
2020-10-23 05:13:14 [INFO ]: Creating trayicon...  (aw_qt.trayicon:140)
2020-10-23 05:13:15 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:40)
2020-10-23 05:13:15 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
WARNING:root:Could not import pymongo, not available as a datastore backend
2020-10-23 05:13:15 [INFO ]: Using storage method: peewee  (aw_server.main:26)
2020-10-23 05:13:15 [INFO ]: Starting up...  (aw_server.main:31)
2020-10-23 05:13:15 [INFO ]: Using database file:  /***/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:90)
 * Serving Flask app "aw-server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-10-23 05:13:15 [INFO ]:  * Running on http://localhost:5600/ (Press CTRL+C to quit)  (werkzeug:122)
2020-10-23 05:13:16 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:348)
2020-10-23 05:13:16 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:348)
2020-10-23 05:13:18 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_or)  (aw_server.api:228)

```

When I click on `trayicon`, from `OpenDashboard`:

```
Opening dashboard
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by kde-open5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5KIOCore.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5I18n.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5CoreAddons.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5JobWidgets.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5Service.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5Completion.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5IconThemes.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigWidgets.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5WindowSystem.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5WidgetsAddons.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigGui.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5ConfigCore.so.5)
kde-open5: ***/activitywatch/activitywatch/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libQt5Xml.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5Crash.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5DBusAddons.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5AuthCore.so.5)
kde-open5: ***/activitywatch/activitywatch/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lib/x86_64-linux-gnu/libfam.so.0)
kde-open5: ***/activitywatch/activitywatch/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /lib/x86_64-linux-gnu/libfam.so.0)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libQt5X11Extras.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5Archive.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5ItemViews.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5Codecs.so.5)
kde-open5: ***/activitywatch/activitywatch/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libKF5GuiAddons.so.5)
```

**Info**:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by johan-bjareholt** [comment] 2020-10-23 05:21
@omidraha Your issue is completely different as it's the "open dashboard" button that doesn't work rather than aw-server not starting.

According to the logs it looks more like it resembles the following issue which will be fixed in the next release
https://github.com/ActivityWatch/activitywatch/issues/208
