### ISSUE TITLE
watcher afk / windows behind proxy (squid)

### ISSUE THREAD

**Issue by OlivierMary** [ActivityWatch/activitywatch#266] opened 2019-01-22 11:07 UTC
## Describe the bug
With my personal PC no problem, but at work with proxy for afk and windows watcher I have this error:

```
2019-01-22 12:02:24 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
2019-01-22 12:02:25 [WARNING]: 503 Server Error: Service Unavailable for url: http://localhost:5600/api/0/buckets/  (aw_client.client:72)
```

no problem with firefox plugin or other plugins

## To Reproduce
1. Setup squid proxy
2. setup windows proxy to squid
3. Start afk or windows proxy

## Expected behavior
No bug

## Environment
 - ActivityWatch version: 0.8.0b7
 - OS: Windows 10

**Comment by johan-bjareholt** [comment] 2019-01-22 11:33
Ah, good point. I used to have that same issue but was able to circumvent it with a small tweak as you can see in this stackoverflow post. I have only tried that quick solution on Linux though, but I assume that it works on windows as well.

https://stackoverflow.com/a/8287752/2127148

In the long run we should probably add a option to set proxy in the aw-client.ini configuration file in aw-client as that would be a simpler fix.

**Comment by OlivierMary** [comment] 2019-01-22 12:14
Hi @johan-bjareholt 

I already have this env var for all my system:
![image](https://user-images.githubusercontent.com/4348675/51534976-8686c000-1e47-11e9-8dcd-5e5dcb53a88c.png)

**Comment by johan-bjareholt** [comment] 2019-01-22 12:15
@OlivierMary Try to set them in lower-case as well

**Comment by OlivierMary** [comment] 2019-01-22 12:17
@johan-bjareholt On windows env var are case insensitive..., but in code if you search it with case sensitive maybe... will try !

**Comment by OlivierMary** [comment] 2019-01-22 12:19
Same,

If that can help you, more log when I start watcher manually (.exe vs tray)
![image](https://user-images.githubusercontent.com/4348675/51535273-483dd080-1e48-11e9-8cb0-ca6906dc886c.png)

**Comment by johan-bjareholt** [comment] 2019-01-22 12:35
That error is different so something makes the code go a different path from your initial report at least. An error occurs while an error is occuring, there's clearly badly written code there which needs to be fixed. So this code is not the root of the problem, but it needs to be fixed to understand what the root of the problem is.

https://github.com/ActivityWatch/aw-client/blob/0cf3de54dd60ded57832b0e6a88649f6bf8f67fd/aw_client/client.py#L74

If I understand this correctly, we should handle the exception json.decoder.JSONDecodeError instead of json.JSONDecodeError. @ErikBjare

**Comment by ErikBjare** [comment] 2019-03-05 09:12
I think that last error is probably due to the proxy returning something that's not JSON, and it seems to me the exception is handled correctly. The documentation states it's called [`json.JSONDecodeError`](https://docs.python.org/3/library/json.html#json.JSONDecodeError) (but is probably located in `json.decode`, although shouldn't matter as the `local variable 'json' referenced before assignment` is the issue, which makes no sense to me in the latest version of the code.

I've recently rewritten that code anyway, and this issue is mostly a curiosity and does not seem to be an actual issue with ActivityWatch, so closing.

**Comment by johan-bjareholt** [comment] 2019-03-05 12:17
How to properly use ActivityWatch with a proxy is not clear though, so I'll re-open this issue until we create a new issue where we describe that we need to document it and possibly also add a configuration in aw-client.ini for it.

**Comment by ErikBjare** [comment] 2019-03-05 14:18
@johan-bjareholt Why not just use an SSH tunnel? Works fine. Using it with a proxy is probably not at all secure.

**Comment by OlivierMary** [comment] 2019-03-05 14:45
We cannot all use ssh tunnel ... The problem is the watcher don't use correctly proxy or internet configuration. And why ? Actually it's only in localhost.... Just one try 127.0.0.1 and another localhost to connect to server. Maybe need to have a common configuration between server / watchers / client GUI. Will be hard if we have to configure proxy or other thing on all watcher / client ... Boring for users.... And when server will be online... A common configuration will be great !

**Comment by OlivierMary** [comment] 2019-03-05 14:49
I use already squid + corkscrew. But if I can't put the proxy conf in worker that cant be ok..




Télécharger Outlook pour Android







On Tue, Mar 5, 2019 at 3:18 PM +0100, "Erik Bjäreholt" <notifications@github.com> wrote:












@johan-bjareholt Why not just use an SSH tunnel? Works fine. Using it with a proxy is probably not at all secure.

**Comment by ErikBjare** [comment] 2019-03-05 16:48
Proxy configuration should just work if you've declared the `HTTP_PROXY` env variable ([as said in the documentation](http://docs.python-requests.org/en/master/user/advanced/#proxies)).

>The problem is the watcher don't use correctly proxy or internet configuration. And why ? Actually it's only in localhost.... Just one try 127.0.0.1 and another localhost to connect to server. Maybe need to have a common configuration between server / watchers / client GUI. Will be hard if we have to configure proxy or other thing on all watcher / client ... Boring for users.... And when server will be online... A common configuration will be great !

I'm really having difficulty understanding what you're trying to say here. As far as I can tell **it is using the proxy configuration correctly**, otherwise you wouldn't get the 503 Service Unavailable error. The issue is most likely the proxy not handling it correctly, as the StackOverflow question I linked above suggested.

This question on SO also suggests it could be a consequence of a proxy configuration issue: https://superuser.com/questions/124897/503-service-unavailable-what-really-it-means

**Comment by ErikBjare** [comment] 2019-03-05 16:52
@johan-bjareholt I really don't see why you reopened the issue. The `requests` library should (and seems to) pick up the proxy configuration correctly from environment variables and the `503` suggests it actually did. What is there for us to do here?

**Comment by ErikBjare** [comment] 2019-03-05 17:02
If it's a issue with Squid not liking the use of `localhost` (for some DNS reason) when connecting to aw-server, try changing `hostname` in `aw-client.ini` to `127.0.0.1` instead of `localhost`. (As the proxy might not like the use of localhost)

You could also try setting the environment variable `NO_PROXY=localhost` which should make the requests lib ignore the proxy settings correctly. (a better option than resetting the environment variable that I wrote about earlier)

**Comment by OlivierMary** [comment] 2019-03-05 17:35
Ok, will try that next week not at work this week... Http_proxy is ok. No_proxy maybe. Will check that.

**Comment by johan-bjareholt** [comment] 2019-03-05 17:55
> Why not just use an SSH tunnel? Works fine. Using it with a proxy is probably not at all secure so we shouldn't put any effort into supporting it anyway.

I'm proposing to document how to make activitywatch avoid using the system-default proxy completely.

> Proxy configuration should just work if you've declared the HTTP_PROXY env variable (as said in the documentation).

We should have this note in our documentation, people shouldn't have to dig through the request library documentation to find a solution.

Also, some people don't know how to set ENV vars, so it might also be a good idea to add a option to aw-client.ini which can override the default system proxy as that will simplify things a lot.

**Comment by ErikBjare** [comment] 2019-03-05 18:02
>We should have this note in our documentation, people shouldn't have to dig through the request library documentation to find a solution.

This is a very common practice for configuring a proxy, and not the issue here.

>Also, some people don't know how to set ENV vars, so it might also be a good idea to add a option to aw-client.ini which can override the default system proxy as that will simplify things a lot.

If anything, we should configure aw-client to ignore proxies from env variables altogether (at least if the address of the server is `127.0.0.1`/`localhost`).

**Comment by johan-bjareholt** [comment] 2019-03-05 18:06
I made an issue for aw-client here, let's discuss the rest there and I'll close this issue.

https://github.com/ActivityWatch/aw-client/issues/41

> If anything, we should configure aw-client to ignore proxies from env variables altogether (at least if the address of the server is 127.0.0.1/localhost).

That might be a good idea, but for now I added a notice in the docs. If that solution solves it nicely we can remove this notice.

https://github.com/ActivityWatch/docs/commit/2cb481c4744e581d6ab837e6e0836586cbf52ec7

**Closed by johan-bjareholt** 2019-03-05 18:06 UTC

**Comment by OlivierMary** [comment] 2019-03-11 10:51
Hi there, I changed all .ini + change to last released and I have now the buckets, but no entries for afk / window...

![image](https://user-images.githubusercontent.com/4348675/54118728-023acd00-43f4-11e9-9c9b-f4fea43cd00c.png)

**Comment by ErikBjare** [comment] 2019-03-11 10:58
@OlivierMary Something is probably wrong with your aw-client configuration, causing the two watchers that use it to fail. Check the logs.

**Comment by OlivierMary** [comment] 2019-03-11 11:41
Hi,




Already check no error...




Just persistent DB in queues directory are very huge 100mb for one...

**Comment by ErikBjare** [comment] 2019-03-11 12:25
>Just persistent DB in queues directory are very huge 100mb for one...

Then they are probably in the process of emptying... Could take a while. Check the raw data tab to see if any new events arrive to the buckets.

**Comment by OlivierMary** [comment] 2019-03-11 12:59
@ErikBjare Yes maybe that, Windows is ok now just AFK no new event count... but a very long AFK timer is growing.... will see. DB size didn't grow down.

**Comment by johan-bjareholt** [comment] 2019-03-11 14:19
It is also a known bug that consuming the queue is much slower on windows than on macOS/Linux. The pre-merge events a few releases ago should have improved this a bit, but if the queue has days of events it might still take hours to be fully worked through. Exactly why it's so slow on windows though I don't know.

**Comment by OlivierMary** [comment] 2019-03-11 15:08
All is good now, that take 4-5h to consume ~1 month.
